src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Criteria__c</fullName>
        <label>Política de Compras</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/customReport__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SCP Custom Report</relationshipLabel>
        <relationshipName>SCP_Custom_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>actionPlan__c</fullName>
        <defaultValue>true</defaultValue>
        <label>actionPlan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>clientContext__c</fullName>
        <defaultValue>true</defaultValue>
        <label>clientContext</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>competitors__c</fullName>
        <defaultValue>true</defaultValue>
        <label>competitors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>growthStrategy__c</fullName>
        <defaultValue>true</defaultValue>
        <label>growthStrategy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>industryTrend__c</fullName>
        <defaultValue>true</defaultValue>
        <label>industryTrend</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>influenceMap__c</fullName>
        <defaultValue>true</defaultValue>
        <label>influenceMap</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kpi__c</fullName>
        <defaultValue>true</defaultValue>
        <label>kpi</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>netActivity__c</fullName>
        <defaultValue>true</defaultValue>
        <label>netActivity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>provenValue__c</fullName>
        <defaultValue>true</defaultValue>
        <label>provenValue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>valueDrivers__c</fullName>
        <defaultValue>true</defaultValue>
        <label>valueDrivers</label>
        <type>Checkbox</type>
    </fields>
    <label>SCP Custom Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Custom Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Custom Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>KPIs</relationshipLabel>
        <relationshipName>KPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SCP Potential New Business</relationshipLabel>
        <relationshipName>GAP_Potential_New_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Strategic_Cnt</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Strategic_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Strategic_Cnt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountCustomReportController.cls
public with sharing class AccountCustomReportController {
    
    public Account account {get;set;}
    public Boolean canEdit {get;set;}
    public CustomReport__c customReport {get;set;}
    
    public AccountCustomReportController() {        
        
        if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible() && Schema.sObjectType.Account.fields.parentId.isAccessible() && Schema.sObjectType.Account.fields.Industry.isAccessible() && Schema.sObjectType.Account.fields.Region__c.isAccessible() && Schema.sObjectType.Account.fields.Sector__C.isAccessible() && Schema.sObjectType.Account.fields.Micro_Industry__c.isAccessible() && Schema.sObjectType.Account.fields.Strategic_Context__c.isAccessible() && Schema.sObjectType.Account.fields.Strategic_Context_Last_Update__c.isAccessible() && Schema.sObjectType.Account.fields.Buying_Criteria__c.isAccessible()  && Schema.sObjectType.Account.fields.Region__c.isAccessible() ){
        account = [SELECT name, id, parentId, Industry, Region__c, Sector__C, Micro_Industry__c, Strategic_Context__c, Strategic_Context_Last_Update__c, Buying_Criteria__c, parent.Name, Region__r.Currency__c, Region__r.Currency_Name__c, (select name, Potential_New_Business__c, Potential_New_Business__r.Name from Potential_New_Business_Strategic_Cnt__r) FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];    
        }
        
        Util.globalAccount = account;
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.Custom_Report_Msg));                
        init();        
    }
    
    private void init() {
        
        List<CustomReport__c> customReportList = new List<CustomReport__c>();
        
        if(Schema.sObjectType.CustomReport__c.isAccessible() && Schema.sObjectType.CustomReport__c.fields.account__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.industryTrend__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.clientContext__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.kpi__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.competitors__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.netActivity__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.influenceMap__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.provenValue__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.valueDrivers__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.growthStrategy__c.isAccessible()  && Schema.sObjectType.CustomReport__c.fields.actionPlan__c.isAccessible()  ){
        customReportList = [select id, account__c, industryTrend__c, clientContext__c, kpi__c, competitors__c, netActivity__c, influenceMap__c, provenValue__c, valueDrivers__c, growthStrategy__c, actionPlan__c from CustomReport__c where account__c = :account.id];   
        }
        
        
        
        if (customReportList.size() > 0) {
            customReport = customReportList.get(0);
        } else {
            customReport = new CustomReport__c(account__c = account.id);
        }
    }
    
    public PageReference save() {
        try {
            if(Schema.sObjectType.CustomReport__c.fields.account__c.isCreateable()
            && Schema.sObjectType.CustomReport__c.isCreateable()
            && Schema.sObjectType.CustomReport__c.fields.account__c.isUpdateable()
            && Schema.sObjectType.CustomReport__c.isUpdateable())
	        upsert customReport;
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        init();
        return null;        
    }
    
    public PageReference ExportToWord() {      
        save();
        return Page.accountCustomReportWord;
    }
    
    public String getWordName() {
        String name = account.Name + '-' + Label.Custom_Report + '.doc';
        return name.replaceAll(' ', '_').replaceAll(',','');
    }

}