src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Industria y Comercio</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Administración pública</fullName>
                </value>
                <value>
                    <fullName>Salud, Educación y Seguridad</fullName>
                </value>
                <value>
                    <fullName>Servicios y Tecnología</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SCP Potential New Business</relationshipLabel>
        <relationshipName>GAP_Potential_New_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Past_Provent__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Past_Provent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Past_Provent</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Past_Provent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Past_Provent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic_Ini__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business - Strategic I</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential New Business - Strategic Ini N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business - Strategic I</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipName>Potential_New_Business_Trend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Trend</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Trend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_accountGrowthStrategy.cls
@isTest
private class Test_accountGrowthStrategy {
	
	static testMethod void myUnitTest() {
    	/* Create Regions */
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__C(name='Regional', parent__c = regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__C(name='Local', parent__c = regionRegional.id);
        insert regionLocal;
        
        List<Region__c> regionsList = [select id from Region__c];
        system.assertEquals(3, regionsList.size());
        
        /* Create Account */
        String industry = 'Industry';
        String micro_industry = 'Micro_Industry';
        
        String accountName = 'Account Test';
        Account acctGrandparent = new Account(Name=accountName, Region__c = regionRegional.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctGrandparent;
        
        Account acctParent = new Account(Name=accountName, Region__c = regionRegional.id, parentId = acctGrandparent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctParent;
        
        Account acct = new Account(Name=accountName, Region__c = regionLocal.id, parentId = acctParent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acct;        
        
        List<Account> accountList = [select id from Account];
        system.assertEquals(3, accountList.size()); 
    	
    	 /* Create Strategic Iniciatives */
        List<Strategic_Initiative__c> strategics = new List<Strategic_Initiative__c>(); 
        
        Strategic_Initiative__c strategicGP = new Strategic_Initiative__c(account__c = acctGrandparent.id);
        strategics.add(strategicGP);
        
        Strategic_Initiative__c strategicP = new Strategic_Initiative__c(account__c = acctParent.id);
        strategics.add(strategicP);
        
        Strategic_Initiative__c strategic = new Strategic_Initiative__c(account__c = acct.id);
        strategics.add(strategic);
        
        insert strategics;
        
        List<Strategic_Initiative__c> strategicList = [select id from Strategic_Initiative__c];
        system.assertEquals(3, strategicList.size());
        
        System.currentPagereference().getParameters().put('id',acct.id);
        AccountGrowthStrategyController agsc = new AccountGrowthStrategyController();
        
        /* Test Strategic Iniciatives */
        system.assertEquals(3,agsc.localStrategicInitiatives.size() + agsc.globalStrategicInitiatives.size());
        
        /* Test Link and UnLink Iniciatives */
        agsc.iniciativeid = strategic.id;
        agsc.linkIniciative();        
        List<Potential_New_Business_Strategic_Ini__c> pnbsList = [select id from Potential_New_Business_Strategic_Ini__c];
        system.assertEquals(1, pnbsList.size());
        
        agsc.iniciativeid = pnbsList.get(0).id;  
        agsc.unlinkIniciative();
        List<Potential_New_Business_Strategic_Ini__c> pnbsList2 = [select id from Potential_New_Business_Strategic_Ini__c];
        system.assertEquals(0, pnbsList2.size());
	}
	
	static testMethod void myUnitTest2() {
    	/* Create Regions */
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__C(name='Regional', parent__c = regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__C(name='Local', parent__c = regionRegional.id);
        insert regionLocal;
        
        List<Region__c> regionsList = [select id from Region__c];
        system.assertEquals(3, regionsList.size());
        
        /* Create Account */
        String industry = 'Industry';
        String micro_industry = 'Micro_Industry';
        
        String accountName = 'Account Test';
        Account acctGrandparent = new Account(Name=accountName, Region__c = regionRegional.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctGrandparent;
        
        Account acctParent = new Account(Name=accountName, Region__c = regionRegional.id, parentId = acctGrandparent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctParent;
        
        Account acct = new Account(Name=accountName, Region__c = regionLocal.id, parentId = acctParent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acct;        
        
        List<Account> accountList = [select id from Account];
        system.assertEquals(3, accountList.size());
    	
    	/* Create Industry Trends */
        List<Industry_Trend__c> industries = new List<Industry_Trend__c>();  
        
        Industry_Trend__c it1 = new Industry_Trend__c();
        it1.sub_sector__c = industry;
        it1.industry__c = micro_industry;
        it1.Region__c = regionGlobal.id;
        it1.trend__c = 'it1';
        industries.add(it1);
        
        Industry_Trend__c it2 = new Industry_Trend__c();
        it2.sub_sector__c = industry;
        it2.industry__c = micro_industry;
        it2.Region__c = regionRegional.id;
        it2.trend__c = 'it2';
        industries.add(it2);
        
        Industry_Trend__c it3 = new Industry_Trend__c();
        it3.sub_sector__c = industry;
        it3.industry__c = micro_industry;
        it3.Region__c = regionLocal.id;
        it3.trend__c = 'it3';
        industries.add(it3);
        
        Industry_Trend__c it4 = new Industry_Trend__c();
        it4.sub_sector__c = industry;
        it4.industry__c = 'All';
        it4.Region__c = regionRegional.id;
        it4.trend__c = 'it4';
        industries.add(it4);
        
        Industry_Trend__c it5 = new Industry_Trend__c();
        it5.sub_sector__c = 'All';
        it5.industry__c = 'All';
        it5.Region__c = regionRegional.id;
        it5.trend__c = 'it5';
        industries.add(it5);
        
        insert industries;
        List<Industry_Trend__c> trendsList = [select id from Industry_Trend__c];
        system.assertEquals(5,trendsList.size());
        
        System.currentPagereference().getParameters().put('id',acct.id);
        AccountGrowthStrategyController agsc = new AccountGrowthStrategyController();
        
        /* Test Industry Trends */
        List<Industry_Trend__c> trendsResultList = new List<Industry_Trend__c>();
        for (ExtendedRegion er :agsc.Regions) {
        	trendsResultList.addAll(er.Trends);
        }
        
        /* Test Link and UnLink Trends */
        agsc.trendid = it1.id;
        agsc.linkTrend();        
        List<Potential_New_Business_Trend__c> pnbtList = [select id from Potential_New_Business_Trend__c];
        system.assertEquals(1, pnbtList.size());
        
        agsc.trendid = pnbtList.get(0).id;
        agsc.unlinkTrend();
        List<Potential_New_Business_Trend__c> pnbtList2 = [select id from Potential_New_Business_Trend__c];
        system.assertEquals(0, pnbtList2.size());
	}
	
	static testMethod void myUnitTest3() {
    	/* Create Regions */
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__C(name='Regional', parent__c = regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__C(name='Local', parent__c = regionRegional.id);
        insert regionLocal;
        
        List<Region__c> regionsList = [select id from Region__c];
        system.assertEquals(3, regionsList.size());
        
        /* Create Account */
        String industry = 'Industry';
        String micro_industry = 'Micro_Industry';
        
        String accountName = 'Account Test';
        Account acctGrandparent = new Account(Name=accountName, Region__c = regionRegional.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctGrandparent;
        
        Account acctParent = new Account(Name=accountName, Region__c = regionRegional.id, parentId = acctGrandparent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acctParent;
        
        Account acct = new Account(Name=accountName, Region__c = regionLocal.id, parentId = acctParent.id, Industry = industry, Micro_Industry__c = micro_industry);
        insert acct;        
        
        List<Account> accountList = [select id from Account];
        system.assertEquals(3, accountList.size());
    	
    	/* Create Proven Value*/
        List<PastProvenValueNew__c> provens = new List<PastProvenValueNew__c>();
        
        PastProvenValueNew__c prov1 = new PastProvenValueNew__c();
        prov1.Industry__c = industry;
        prov1.Micro_Industry__c = micro_industry;
        prov1.region__c = regionGlobal.id;
        prov1.Unique_Value__c = 'prov1'; 
        provens.add(prov1);
        
        PastProvenValueNew__c prov2 = new PastProvenValueNew__c();
        prov2.Industry__c = industry;
        prov2.Micro_Industry__c = micro_industry;
        prov2.region__c = regionRegional.id;
        prov2.Unique_Value__c = 'prov2';
        provens.add(prov2);
        
        PastProvenValueNew__c prov3 = new PastProvenValueNew__c();
        prov3.Industry__c = industry;
        prov3.Micro_Industry__c = micro_industry;
        prov3.region__c = regionLocal.id;
        prov3.Unique_Value__c = 'prov3';
        provens.add(prov3);
        
        PastProvenValueNew__c prov4 = new PastProvenValueNew__c();
        prov4.Industry__c = industry;
        prov4.Micro_Industry__c = 'All';
        prov4.region__c = regionLocal.id;
        prov4.Unique_Value__c = 'prov4';
        provens.add(prov4);
        
        PastProvenValueNew__c prov5 = new PastProvenValueNew__c();
        prov5.Industry__c = 'All';
        prov5.Micro_Industry__c = 'All';
        prov5.region__c = regionLocal.id;
        prov5.Unique_Value__c = 'prov5';
        provens.add(prov5);
        
        PastProvenValueNew__c prov6 = new PastProvenValueNew__c();
        prov6.account__c = acct.id;
        prov6.Unique_Value__c = 'prov6';
        provens.add(prov6);
        
        PastProvenValueNew__c prov7 = new PastProvenValueNew__c();
        prov7.account__c = acctParent.id;
        prov7.Unique_Value__c = 'prov7';
        provens.add(prov7);
        
        insert provens;
        
        List<PastProvenValueNew__c> provList = [select id from PastProvenValueNew__c];
        system.assertEquals(7, provList.size()); 
        
        System.currentPagereference().getParameters().put('id',acct.id);
        AccountGrowthStrategyController agsc = new AccountGrowthStrategyController();
        
        /* Test Proven Value*/
        system.assertEquals(7, agsc.provenValueWrapperList.size(), agsc.provenValueWrapperList);
        
        agsc.add();
        List<Potential_New_Business__c> potentialsList = [select id from Potential_New_Business__c where account__c = :acct.id];
        
        system.assertEquals(1, potentialsList.size());
        system.assertEquals(agsc.PotentialNewBusinessList.size(), potentialsList.size());
        
        agsc.PotentialNewBusinessList.get(0).Potential_new_Business__c = 'Test';

        agsc.save();
        
        List<Potential_New_Business__c> potentialsList2 = [select id from Potential_New_Business__c where account__c = :acct.id and Potential_new_Business__c = 'Test'];        
        system.assertEquals(1, potentialsList2.size());
        
        agsc.pnbid = agsc.PotentialNewBusinessList.get(0).id;
        
        /* Test Link and UnLink Proven Value */
        agsc.pastProventValueid = prov1.id;
        agsc.linkPastProventValue();        
        List<Potential_New_Business_Past_Provent__c> pnbpList = [select id from Potential_New_Business_Past_Provent__c];
        system.assertEquals(1, pnbpList.size());
        
        agsc.pastProventValueid = pnbpList.get(0).id;
        agsc.unlinkPastProventValue();
        List<Potential_New_Business_Past_Provent__c> pnbpList2 = [select id from Potential_New_Business_Past_Provent__c];
        system.assertEquals(0, pnbpList2.size());
        
        /* Export */
        agsc.getExcelName();
        agsc.ExportToExcel();
	}
	
	
}