src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoría WH</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RP</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>TT</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>EI</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>EO</fullName>
                </value>
                <value>
                    <fullName>ET</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>OO</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contenedor_de_hito2__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contenedor de hitos2</relationshipLabel>
        <relationshipName>Contenedor_de_hitos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contenedor de hito2</label>
    <nameField>
        <label>Nombre de Contenedor_de_hito2__c</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenedor de hitos2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hito_Relevante_2__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vencimiento Contrato Activo con Nosotros</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato Activo con la Competencia</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP TI</fullName>
                </value>
                <value>
                    <fullName>Evento Para Nuestros Clientes</fullName>
                </value>
                <value>
                    <fullName>Evento Relevante de la Industria</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato del Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <label>Hito Relevante 2</label>
    <nameField>
        <label>Nombre de Hito Relevante 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos Relevantes 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HitosRelevantesTest.cls
@isTest
public class HitosRelevantesTest {
	
    static testMethod void test1() {
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Contenedor_de_hito2__c contenedorHito = new Contenedor_de_hito2__c();
        contenedorHito.name = 'Contenedor';
        contenedorHito.Cuenta__c = cuenta.id;
        insert contenedorHito;
        
        
         Hito_Relevante_2__c hito2 = new Hito_Relevante_2__c();
        hito2.name = 'hito';
        
        Hito_Relevante_2__c hito = new Hito_Relevante_2__c();
        hito.name = 'hito';
        
       
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        HitosRelevantesController controller = new HitosRelevantesController();
        
        controller.hitoAInsertar = hito;
        controller.insertHito();
        controller.guardar();
        
        controller.hitoAInsertar = hito2;
        controller.insertHito();
        controller.guardar();
        
        List<Hito_Relevante_2__c> hitos = new List<Hito_Relevante_2__c>();
        hitos = [select id, Categoria__c, Descripcion__c, Fecha__c from Hito_Relevante_2__c];
        
        system.assertEquals(2, hitos.size());
        
        controller.hitoABorrarId = hito2.id;
        controller.BorrarHito();
        controller.guardar();
        
        hitos = [select id, Categoria__c, Descripcion__c, Fecha__c from Hito_Relevante_2__c];
        
        system.assertEquals(1, hitos.size());
        
        system.assertEquals(controller.idCuenta, cuenta.id);
        
    }
    
    
    static testMethod void test2() {
        
        //Sin contenedor de hito creado
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Hito_Relevante_2__c hito = new Hito_Relevante_2__c();
        hito.name = 'hito';
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        HitosRelevantesController controller = new HitosRelevantesController();
        
        controller.hitoAInsertar = hito;
        controller.insertHito();
        
        List<Hito_Relevante_2__c> hitos = new List<Hito_Relevante_2__c>();
        hitos = [select id, Categoria__c, Descripcion__c, Fecha__c from Hito_Relevante_2__c];
        
        system.assertEquals(1, hitos.size());
        
        controller.hitoABorrarId = hito.id;
        controller.BorrarHito();
        
        hitos = [select id, Categoria__c, Descripcion__c, Fecha__c from Hito_Relevante_2__c];
        
        system.assertEquals(0, hitos.size());
        
    }
}