src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoría WH</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RP</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>TT</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>EI</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>EO</fullName>
                </value>
                <value>
                    <fullName>ET</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>OO</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Area_de_trabajo__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Areas de trabajo</relationshipLabel>
        <relationshipName>Areas_de_trabajo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Area de trabajo</label>
    <nameField>
        <label>Nombre de Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas de trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contenedor_de_hito__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contenedor de hitos</relationshipLabel>
        <relationshipName>Contenedor_de_hitos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contenedor de hito</label>
    <nameField>
        <label>Nombre de Contenedor de hito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenedor de hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hito_relevante__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vencimiento Contrato Activo con Nosotros</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato Activo con la Competencia</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP TI</fullName>
                </value>
                <value>
                    <fullName>Evento Para Nuestros Clientes</fullName>
                </value>
                <value>
                    <fullName>Evento Relevante de la Industria</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato del Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contenedor_de_hito__c</fullName>
        <label>Contenedor de hito</label>
        <referenceTo>Contenedor_de_hito__c</referenceTo>
        <relationshipLabel>Hitos relevantes</relationshipLabel>
        <relationshipName>Hitos_relevantes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <label>Hito relevante</label>
    <nameField>
        <label>Nombre de Hitos relevantes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos relevantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto__c.object
<CustomObject>
    <fields>
        <fullName>Area_de_trabajo__c</fullName>
        <label>Area de trabajo</label>
        <referenceTo>Area_de_trabajo__c</referenceTo>
        <relationshipLabel>Retos</relationshipLabel>
        <relationshipName>Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_Compromiso__c</fullName>
        <label>Fecha Compromiso</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nota__c</fullName>
        <label>Nota</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Reto</label>
    <nameField>
        <label>Nombre de Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCPTabTest.cls
@isTest
public class SCPTabTest {
	
    static testMethod void test(){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Area_de_trabajo__c area = new Area_de_trabajo__c();
        area.Name = 'area1';
        area.Cuenta__c = cuenta.id;
        insert area;
        
        Reto__c reto = new Reto__c();
        reto.Name = 'reto1';
        reto.Area_de_trabajo__c = area.id;
        reto.Fecha_Compromiso__c = Date.today();
        reto.Nombre_del_Reto__c = 'nombrereto';
        reto.Nota__c = 'dasdasdasdas';
        insert reto;
        
        Contenedor_de_hito__c contenedorHito = new Contenedor_de_hito__c();
        contenedorHito.name = 'Contenedor';
        contenedorHito.Cuenta__c = cuenta.id;
        insert contenedorHito;
        
        Hito_Relevante__c hito = new Hito_Relevante__c();
        hito.name = 'hito';
        hito.Contenedor_de_hito__c = contenedorHito.id;
        hito.Fecha__c = Date.today();
        hito.Categoria__c = 'Vencimiento Contrato Activo con la Competencia';
        hito.Descripcion__c = 'dasdasas';
        
        insert hito;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        SCPTabController controller = new SCPTabController();
        
        controller.filtroVencimiento = true;
        controller.filtroEventoTelefonica = true;
        controller.filtroEventosDeTipoReto = true;
        controller.filtroVencimientoCompetencia = true;
        controller.filtroPublicacionRFPComunicacion = true;
        controller.filtroPublicacionRFPTI = true;
        controller.filtroEventoIndustria = true;
        controller.filtroPrevisionTOP3 = true;
        controller.filtroOtroTipoDeEvento = true;
   		controller.todos = true;        
        
        controller.filtroDeNombre = '';
        controller.filtrar();
        
        system.assertEquals(1, controller.setCuentas.getRecords().size());
        
        controller.filtroDeNombre = 'Cuent';
        controller.filtrar();
        
        system.assertEquals(1, controller.setCuentas.getRecords().size());
        
        controller.establecerValoresDeLaLineaDeTiempo();
        controller.obtenerAnterior();
        controller.obtenerSiguiente();
        controller.obtenerPrimerPagina();
        controller.obtenerUltimaPagina();
        controller.filtrarTimeLine();
        
        List<Reto__c> listaRetos = new List<Reto__c>();
        listaRetos.add(reto);
        
        controller.generarDatosRetos(listaRetos);
       
        
    }
}