src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Value_Proposition__c</fullName>
        <label>Value Proposition</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/OpportunityPastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Opportunity - PastProvenValueNew</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityPastProvenValueNew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Opportunity - PastProvenValueNew</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_OpportunitySnapshot.cls
@isTest
private class Test_OpportunitySnapshot {

    static testMethod void myUnitTest() {
		
		/* Create Region */
		Region__c regionGlobal = new Region__C(name='Global');
        regionGlobal.Currency_Name__c ='asd';
        insert regionGlobal;
		
		/* Create Account */
		String accountName = 'Account Test';
		Account acct = new Account(Name=accountName, Region__c=regionGlobal.id);
		insert acct;
		
		List<Account> acctResult = [select id from Account where name = :accountName];
		system.Assert(acctResult.size()>0, 'Error to create Account: ' + acct);
		
		Opportunity opp = new Opportunity(name='Test Opp', accountId = acct.id, stageName = 'Open', closeDate = system.today());
		insert opp;
		
		Industry_Trend__c trend = new Industry_Trend__c(Region__c=regionGlobal.id);
		insert trend;
		OportunityIndustryTrend__c oppIndTrd = new OportunityIndustryTrend__c(Opportunity__c = opp.id, Industry_Trend__c = trend.id);
		insert oppIndTrd;
		
		Strategic_Initiative__c strategic = new Strategic_Initiative__c();
		insert strategic;
		OpportunityStrategicInitiative__c oppStrIni = new OpportunityStrategicInitiative__c(Opportunity__c = opp.id, Strategic_Initiative__c=strategic.id);
		insert oppStrIni;
		
		OpportunityPastProvenValueNew__c oppPtPrVa = new OpportunityPastProvenValueNew__c(Opportunity__c = opp.id);
		insert oppPtPrVa;
		
		/* Set Page and Create Controller*/
		ApexPages.StandardController sc = new ApexPages.StandardController(opp);
		OpportunitySnapshotController oppSnpCtr = new OpportunitySnapshotController(sc);
		
		system.assert(oppSnpCtr.valueArgumentsList.size()==3);
		
		oppSnpCtr.opp.Value_Proposition__c = 'Test Value Proposition';
		oppSnpCtr.save();		
		
		Opportunity oppResult = [select id, Value_Proposition__c from Opportunity where id = :opp.id];		
		system.assertEquals(oppSnpCtr.opp.Value_Proposition__c, oppResult.Value_Proposition__c);
		
		Task t = new Task(WhatId = opp.id);
		insert t;
		
		OpportunitySnapshotController oppSnpCtr2 = new OpportunitySnapshotController(sc);
		
		system.assert(oppSnpCtr2.taskList.size()==1);
		
		oppSnpCtr2.taskList.get(0).description__c = 'Test Description';
		
		oppSnpCtr2.saveTask();
		Task taskResult = [select id, description__c from Task where id = :t.id];
		system.assertEquals(oppSnpCtr2.taskList.get(0).description__c, taskResult.description__c);
		
    }
}