src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/KPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>KPIs</relationshipLabel>
        <relationshipName>KPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub_Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Recreation</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <recordTypes>
        <fullName>KPI</fullName>
        <active>true</active>
        <label>KPI</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_accountKPIWindow.cls
@isTest
private class test_accountKPIWindow {
	
    static testMethod void myUnitTest2() {
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__C(name='Region',Parent__c=regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionRegional.id);
        insert regionLocal;
        
        Account cuentaPadre =new Account();
        cuentaPadre.Name='testPadre';
        cuentaPadre.Region__c=regionGlobal.id;
        
        insert cuentaPadre;
        
        String industry = 'Financial';
        String micro_industry = 'Bank';
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.industry = industry;
        cuenta.micro_industry__c = micro_industry;
        cuenta.ParentId = cuentaPadre.id;
        
        insert cuenta;
        
        List<KPI__c> kpiList = new List<KPI__c>();
        
        //Kpi Parent
        KPI__c temp = new KPI__c();
        temp.Name__c = 'Parent KPI';
        temp.Unit__c = 'Units';
        temp.Region__c = regionLocal.id;
        temp.Account__c = cuentaPadre.id;
        kpiList.add(temp);
        
        //Kpi Account
        KPI__c accountKPI = new KPI__c();
        accountKPI.Name__c = 'Account KPI';
        accountKPI.Unit__c = 'Units';
        accountKPI.Region__c = regionLocal.id;
        accountKPI.Account__c = cuenta.id;
        kpiList.add(accountKPI);
        
        //Kpis Global.
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionGlobal.id;
        temp.Industry__c = 'All';
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionGlobal.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionGlobal.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = industry;
        kpiList.add(temp);
        
        //Kpis Regional
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionRegional.id;
        temp.Industry__c = 'All';
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionRegional.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionRegional.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = industry;
        kpiList.add(temp);
        
        //Kpis Local
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionLocal.id;
        temp.Industry__c = 'All';
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionLocal.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = 'All';
        kpiList.add(temp);
        
        temp = new KPI__c();
        temp.Name__c = 'Number of Branches';
        temp.Unit__c = 'Units';
        temp.Region__c = regionLocal.id;
        temp.Industry__c = micro_industry;
        temp.Sub_Sector__c = industry;
        kpiList.add(temp);
        
        insert kpiList;  
        
        System.currentPagereference().getParameters().put('id',cuenta.id);
        accountKPIWindow p_Test = new accountKPIWindow();
        
        System.assertEquals(1, p_Test.parentData.size());
        
        System.assertEquals(1, p_Test.localData.size());
        
        //System.assertEquals(9, p_Test.Data.size());
        
        p_Test.SaveChanges();
        p_Test.addKPI();
        
        System.assertEquals(2, p_Test.localData.size());
		
		p_Test.getIndustry();
        p_Test.ExportToExcel();
        p_Test.getExcelName();        
        p_Test.delid = accountKPI.id;
        p_Test.deleteKPI();
        
        System.assertEquals(1, p_Test.localData.size());
        
    }
}