src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Project/Capability Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Titulo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Past_Provent__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Past_Provent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Past_Provent</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Past_Provent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Past_Provent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Strategic_Cnt</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Strategic_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Strategic_Cnt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic_Ini__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business - Strategic I</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential New Business - Strategic Ini N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business - Strategic I</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Trend</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Trend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Titulo</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountGrowthStrategyController.cls
public with sharing class AccountGrowthStrategyController {

    public Account account {get;set;}
    public Boolean canEdit {get;set;}
 
    public Id toDel {get;set;}
    
    public List<Strategic_Initiative__c>  localStrategicInitiatives { get; set; }
    public List<Strategic_Initiative__c>  globalStrategicInitiatives { get; set; }
    public List<ExtendedRegion> Regions {get;set;}

    public List<AccountPastProvenValueNewController.ProvenValueWrapper> provenValueWrapperList {get;set;}
    
    public List<Potential_New_Business__c> PotentialNewBusinessList {get;set;}
    public Potential_New_Business__c potentialNewBusiness {get;set;}
    
        public String pnbid {
        get;
        // *** setter is NOT being called ***
        set {
            pnbid = value;
        }
    }
    public String trendid {
        get;
        // *** setter is NOT being called ***
        set {
            trendid = value;
        }
    }

    public String iniciativeid {
        get;
        // *** setter is NOT being called ***
        set {
            iniciativeid = value;
        }
    }
    
    public String pastProventValueid {
        get;
        // *** setter is NOT being called ***
        set {
            pastProventValueid = value;
        }
    }   
  
    public AccountGrowthStrategyController() {        
        if (Util.globalAccount==null) {
        	if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible() && Schema.sObjectType.Account.fields.parentId.isAccessible() && Schema.sObjectType.Account.fields.Industry.isAccessible() && Schema.sObjectType.Account.fields.Region__c.isAccessible() && Schema.sObjectType.Account.fields.Micro_Industry__c.isAccessible() && Schema.sObjectType.Account.fields.Strategic_Context__c.isAccessible() && Schema.sObjectType.Account.fields.Strategic_Context_Last_Update__c.isAccessible() ){
        	account = [SELECT name, id, parentId, Industry, Region__c, /*Sector__C,*/ Micro_Industry__c, Strategic_Context__c, Strategic_Context_Last_Update__c, /*(select id from OpportunityStrategicContext__r),*/ (select name, Potential_New_Business__c, Potential_New_Business__r.Name from Potential_New_Business_Strategic_Cnt__r) FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
        	}
        } else {
    		this.account = Util.globalAccount; 
    	}
        
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);                
        init();        
    }
    
    private void init() {
 
        toDel = null;
        
        if(Schema.sObjectType.Strategic_Initiative__c.isAccessible() && Schema.sObjectType.Strategic_Initiative__c.fields.Name.isAccessible() && Schema.sObjectType.Strategic_Initiative__c.fields.title__c.isAccessible() && Schema.sObjectType.Strategic_Initiative__c.fields.Strategic_Initiative__c.isAccessible() && Schema.sObjectType.Strategic_Initiative__c.fields.LastModifiedDate.isAccessible() ){        
        localStrategicInitiatives = [SELECT title__c , name, Strategic_Initiative__c, LastModifiedDate, (select id from Opportunities__r where opportunity__r.accountId = :account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Strategic_Ini__r) FROM Strategic_Initiative__c WHERE Account__C = :this.account.id];
        }
        globalStrategicInitiatives = new List<Strategic_Initiative__c>();
 
        provenValueWrapperList = new AccountPastProvenValueNewController().provenValueWrapperList;
        
        Region__c region = Util.getRegionFromAccount(account.Id, account.region__c);
                
        Regions = new List<ExtendedRegion>();
        loadData(region);
                
        if(account.parentId != null) {
            //getDataFromParents([SELECT name, id, parentId, Industry,Region__c, Strategic_Context__c, Strategic_Context_Last_Update__c /*, (select name, Opportunity__c from OpportunityStrategicContext__r)*/ FROM Account WHERE Id = :this.account.parentId]);        
            getDataFromParents();
        }
        if(Schema.sObjectType.Potential_New_Business__c.isAccessible() 
        && Schema.sObjectType.Potential_New_Business__c.fields.Name.isAccessible() 
        && Schema.sObjectType.Potential_New_Business__c.fields.Comments__c.isAccessible() 
        && Schema.sObjectType.Potential_New_Business__c.fields.Contact_to_approach__c.isAccessible()
        && Schema.sObjectType.Potential_New_Business__c.fields.Estimated_FCV__c.isAccessible()
        && Schema.sObjectType.Potential_New_Business__c.fields.Potential_new_Business__c.isAccessible()
        && Schema.sObjectType.Potential_New_Business__c.fields.Status__c.isAccessible() ){
        PotentialNewBusinessList = [select id, Name, Comments__c, Contact_to_approach__c, Estimated_FCV__c, Potential_new_Business__c, Status__c, (SELECT Industry_Trend__c, Industry_Trend__r.name, Industry_Trend__r.Trend__c FROM Potential_New_Business_Trend__r), (SELECT Strategic_Initiative__c, Strategic_Initiative__r.name, Strategic_Initiative__r.Strategic_Initiative__c FROM Potential_New_Business_Strategic_Ini__r ORDER BY Strategic_Initiative__r.name DESC), (select Past_Proven_Value__c, Past_Proven_Value__r.Name, Past_Proven_Value__r.Unique_Value__c from Potential_New_Business_Past_Provent__r) from Potential_New_Business__c where account__c = :account.id];
        }
        
        potentialNewBusiness = new  Potential_New_Business__c(Account__c = account.id); 
    }
    
    public void loadData(Region__c region){
    	        
        Map<Id, Region__c> regionsMap = new Map<Id, Region__c>();
        List<Region__c> regiones = new List<Region__c>();
        
        if(Schema.sObjectType.Region__c.isAccessible() && Schema.sObjectType.Region__c.fields.parent__c.isAccessible() && Schema.sObjectType.Region__c.fields.Name.isAccessible() ){
        regiones = [select id, Name, parent__c from Region__c limit 1000];
        }
        
        for (Region__c reg :regiones) {
        	regionsMap.put(reg.id,reg);        	
        } 
        
        List<Region__c> regionsToSerch = new List<Region__c>();
        Id regionId = region.id;
        
        while (regionId != null) {
        	Region__c r = regionsMap.get(regionId);
        	regionsToSerch.add(r);
        	regionId = r.parent__c;
        }
        
        List< Industry_Trend__c > Trends = new List< Industry_Trend__c >();
        
        if(Schema.sObjectType.Industry_Trend__c.isAccessible() 
        && Schema.sObjectType.Industry_Trend__c.fields.LastModifiedDate.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.type__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Title__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Name.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Trend__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.URL_Attachment__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Region__c.isAccessible()){
        Trends = [SELECT LastModifiedDate, type__c, Title__c, Name, Trend__c, URL_Attachment__c, Region__c, 
                                           (SELECT id FROM Opportunities__r WHERE opportunity__r.accountId = :account.id), 
                                           (SELECT name, Potential_New_Business__c, Potential_New_Business__r.name, Potential_New_Business__r.Potential_New_Business__c 
                                            FROM Potential_New_Business_Trend__r) 
                                            FROM Industry_Trend__c 
                                            WHERE Region__c in :regionsToSerch AND 
                                            (Sub_Sector__c = :account.Industry OR Sub_Sector__c = 'Todos' OR Sub_Sector__c = 'All') AND 
                                            (Industry__c = :account.Micro_Industry__c OR Industry__c = 'Todos' OR Industry__c = 'All') AND
                                            (type__c = 'Tendencias' OR type__c = 'Casos de éxito Sectorial') 
                                            ORDER BY Name ASC];
        }
 		Map<Id,List<Industry_Trend__c>> regionTrendsMap = new Map<Id,List<Industry_Trend__c>>();
 		
 		for (Industry_Trend__c trend :Trends) {
 			if (regionTrendsMap.get(trend.Region__c) == null) {
 				regionTrendsMap.put(trend.Region__c, new List<Industry_Trend__c>());
 			}
 			regionTrendsMap.get(trend.Region__c).add(trend);
 		}
 		
 		for (Id regId :regionTrendsMap.keySet()) {			
	        Regions.add(new ExtendedRegion(regionsMap.get(regId),regionTrendsMap.get(regId)));
 		}
    }
    
    public void getDataFromParents() {    	
    	List<Id> parentAccountIds = new List<Id>(); 
    	Account parent = new Account();
    	
    	if (account.parentId != null) {
    		parentAccountIds.add(account.parentId);
    		if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible() && Schema.sObjectType.Account.fields.parentId.isAccessible() ){
    		parent = [select id, Name, parentId, parent.parentId from account where id = :account.parentId];
    		}
    		if (parent.parentId != null) {
    			parentAccountIds.add(parent.parentId);
    			if (parent.parent.parentId != null) {
    				parentAccountIds.add(parent.parent.parentId);	
    			}	
    		}
    	}
    	
    	List<Strategic_Initiative__c> temp = new List<Strategic_Initiative__c>();
    	
    	if(Schema.sObjectType.Strategic_Initiative__c.isAccessible() && Schema.sObjectType.Strategic_Initiative__c.fields.Title__c.isAccessible()
    	&& Schema.sObjectType.Strategic_Initiative__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.Strategic_Initiative__c.fields.Strategic_Initiative__c.isAccessible()
    	&& Schema.sObjectType.Strategic_Initiative__c.fields.LastModifiedDate.isAccessible()){
    	temp = [SELECT Title__c, name, Strategic_Initiative__c, LastModifiedDate, (select id from Opportunities__r where opportunity__r.accountId = :account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Strategic_Ini__r) FROM Strategic_Initiative__c WHERE Account__C in :parentAccountIds];
    	}
                
        if(temp != null) {
            globalStrategicInitiatives.addAll(temp);
        }
    	
    }
    
    public PageReference save() {
        try {
            if(Schema.sObjectType.Potential_New_Business__c.isUpdateable() 
        && Schema.sObjectType.Potential_New_Business__c.fields.Comments__c.isUpdateable() 
        && Schema.sObjectType.Potential_New_Business__c.fields.Contact_to_approach__c.isUpdateable()
        && Schema.sObjectType.Potential_New_Business__c.fields.Estimated_FCV__c.isUpdateable()
        && Schema.sObjectType.Potential_New_Business__c.fields.Potential_new_Business__c.isUpdateable()
        && Schema.sObjectType.Potential_New_Business__c.fields.Status__c.isUpdateable() ){
	        update PotentialNewBusinessList;
        }
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        init();
        return null;        
    }
    
    public PageReference add() {
        try {
            
            if(Schema.sObjectType.Potential_New_Business__c.isUpdateable() 

               && Schema.sObjectType.Potential_New_Business__c.fields.Comments__c.isUpdateable() 
               && Schema.sObjectType.Potential_New_Business__c.fields.Contact_to_approach__c.isUpdateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Estimated_FCV__c.isUpdateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Potential_new_Business__c.isUpdateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Status__c.isUpdateable()
               && Schema.sObjectType.Potential_New_Business__c.isCreateable() 

               && Schema.sObjectType.Potential_New_Business__c.fields.Comments__c.isCreateable() 
               && Schema.sObjectType.Potential_New_Business__c.fields.Contact_to_approach__c.isCreateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Estimated_FCV__c.isCreateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Potential_new_Business__c.isCreateable()
               && Schema.sObjectType.Potential_New_Business__c.fields.Status__c.isCreateable() ){
					upsert potentialNewBusiness;
               }
	        
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        init();
        return null;        
    }
    
    public PageReference linkTrend() {        
        try {
            
            if(Schema.sObjectType.Potential_New_Business_Trend__c.fields.Industry_Trend__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Trend__c.fields.Potential_New_Business__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Trend__c.isCreateable()){
	            insert new Potential_New_Business_Trend__c(Industry_Trend__c = trendid, Potential_New_Business__c = pnbid);
            }
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();
        return null;
    }

    public PageReference linkIniciative() {
        try {
            
            if(Schema.sObjectType.Potential_New_Business_Strategic_Ini__c.fields.Strategic_Initiative__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Strategic_Ini__c.fields.Potential_New_Business__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Strategic_Ini__c.isCreateable()){
	            insert new Potential_New_Business_Strategic_Ini__c(Strategic_Initiative__c = iniciativeid, Potential_New_Business__c = pnbid);
            }
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();        
        return null;
    }
    
    public PageReference linkPastProventValue() {
        try {
            
            if(Schema.sObjectType.Potential_New_Business_Past_Provent__c.fields.Past_Proven_Value__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Past_Provent__c.fields.Potential_New_Business__c.isCreateable() &&
            Schema.sObjectType.Potential_New_Business_Past_Provent__c.isCreateable()){
	            insert new Potential_New_Business_Past_Provent__c(Past_Proven_Value__c = pastProventValueid, Potential_New_Business__c = pnbid);
            }
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();
        return null;
    }
   
    public PageReference unlinkTrend() {
        try {
	        
           Potential_New_Business_Trend__c aBorrar = new Potential_New_Business_Trend__c();
           if(Schema.sObjectType.Potential_New_Business_Trend__c.isAccessible()){
           aBorrar = [SELECT id FROM Potential_New_Business_Trend__c WHERE id = :trendid];
           }
           if(Potential_New_Business_Trend__c.sObjectType.getDescribe().isDeletable()){
                delete aBorrar;
            }
        
        
        
        } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();
        return null;
    }
    
    
    
    
	
    public PageReference unlinkIniciative() {
        try {
	        
           Potential_New_Business_Strategic_Ini__c aBorrar = new Potential_New_Business_Strategic_Ini__c();
          if(Schema.sObjectType.Potential_New_Business_Strategic_Ini__c.isAccessible()){
           aBorrar = [SELECT id FROM Potential_New_Business_Strategic_Ini__c WHERE id = :iniciativeid];
          }
           if(Potential_New_Business_Strategic_Ini__c.sObjectType.getDescribe().isDeletable()){
               delete aBorrar;
           }
                      
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();
        return null;
    }
    
    public PageReference unlinkPastProventValue() {
        try {
	        
           Potential_New_Business_Past_Provent__c aBorrar = new Potential_New_Business_Past_Provent__c();
            if(Schema.sObjectType.Potential_New_Business_Past_Provent__c.isAccessible()){
           aBorrar = [SELECT id FROM Potential_New_Business_Past_Provent__c WHERE id = :pastProventValueid];
            }
           if(Potential_New_Business_Past_Provent__c.sObjectType.getDescribe().isDeletable()){
               delete aBorrar;
           }
           
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        save();
        return null;
    }
   
    public PageReference ExportToExcel() {      
        save();
        return Page.accountGrowthStrategyExcel;
    }
    
    public String getExcelName() {
        String name = account.Name + '-' + Label.GAP_Growth_Strategy + '.xls';
        return name.replaceAll(' ', '_').replaceAll(',','');
    }
     
}