src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segmento_Vertical__c</fullName>
        <label>Segmento Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administración Pública, Defensa y Seguridad Social</fullName>
                </value>
                <value>
                    <fullName>Agricultura, Ganadería, Caza y Silvicultura</fullName>
                </value>
                <value>
                    <fullName>Asociaciones e Instituciones</fullName>
                </value>
                <value>
                    <fullName>Automotores - Autopartistas</fullName>
                </value>
                <value>
                    <fullName>Automotores - Concesionarios</fullName>
                </value>
                <value>
                    <fullName>Automotores - Industria Automotriz</fullName>
                </value>
                <value>
                    <fullName>Construcción</fullName>
                </value>
                <value>
                    <fullName>Consultoras</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Entretenimiento</fullName>
                </value>
                <value>
                    <fullName>Explotación de Minas y Canteras</fullName>
                </value>
                <value>
                    <fullName>Gobierno Extranjero</fullName>
                </value>
                <value>
                    <fullName>Gobierno Municipal</fullName>
                </value>
                <value>
                    <fullName>Gobierno Nacional</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Industria Alimenticia</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industrias - Otro</fullName>
                </value>
                <value>
                    <fullName>Logística</fullName>
                </value>
                <value>
                    <fullName>Manufactura</fullName>
                </value>
                <value>
                    <fullName>Medios de Comunicación</fullName>
                </value>
                <value>
                    <fullName>Petróleo</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Agua</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Correos</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Energía</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - GAS</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Transporte</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud - Clínicas, Sanatorios y Hospitales</fullName>
                </value>
                <value>
                    <fullName>Salud - Laboratorios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Account_Industry_trend__c.object
<CustomObject>
    <fields>
        <fullName>Current_state__c</fullName>
        <label>Estado Actual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vendido en el pasado</fullName>
                </value>
                <value>
                    <fullName>No aplica</fullName>
                </value>
                <value>
                    <fullName>Lo poseo en el funnel</fullName>
                </value>
                <value>
                    <fullName>No lo poseo y no lo tengo en perspectiva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Accounts &amp; Industry Trends</relationshipLabel>
        <relationshipName>Accounts_Industry_Trends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account - Industry trend</label>
    <nameField>
        <label>Nombre de Account - Industry trend</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RelatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relacionado con</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>Industry_Trends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Industria y Comercio</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Administración pública</fullName>
                </value>
                <value>
                    <fullName>Salud, Educación y Seguridad</fullName>
                </value>
                <value>
                    <fullName>Servicios y Tecnología</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contexto General</fullName>
                </value>
                <value>
                    <fullName>Métricas y Análisis del Mercado</fullName>
                </value>
                <value>
                    <fullName>Principales Players</fullName>
                </value>
                <value>
                    <fullName>Cadena de Valor y Procesos</fullName>
                </value>
                <value>
                    <fullName>Tendencias</fullName>
                </value>
                <value>
                    <fullName>Casos de éxito Sectorial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Attachment__c</fullName>
        <label>URL Attachment</label>
        <type>Url</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/accountIndustryTrendsNew.cls
public with sharing class accountIndustryTrendsNew {
	
	public List<Industry_Trend__c> trends {get;set;}
	public Boolean canEdit {get;set;}
	public Account account {get;set;}
	public List<TrendsWrapper> trendsWrapperList {get;set;}
    public List<SolutionWrapper> Solutions {get; set;}
    public String SolutionsLabel {get; set;}
    
	public accountIndustryTrendsNew(){
        loadData();
        //Funcion que engloba si el el usuario acutal puede o no escribir en esta cuenta
        userActions temp = new userActions();
        
        canEdit = temp.checkWrite(this.account.id);
    }
    
    public void loadData(){
    	if (Util.globalAccount==null) {
        	if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible()
        	&& Schema.sObjectType.Account.fields.parentId.isAccessible()
        	&& Schema.sObjectType.Account.fields.Industry.isAccessible()
        	&& Schema.sObjectType.Account.fields.Region__c.isAccessible()
        	&& Schema.sObjectType.Account.fields.Sector__C.isAccessible()
        	&& Schema.sObjectType.Account.fields.Micro_Industry__c.isAccessible()
        	&& Schema.sObjectType.Account.fields.Strategic_Context_Last_Update__c.isAccessible()
        	&& Schema.sObjectType.Account.fields.Strategic_Context__c.isAccessible()){
        	account = [SELECT name, id, parentId, Segmento_Vertical__c, Industry, Region__c, Sector__C, Micro_Industry__c, Strategic_Context__c, Strategic_Context_Last_Update__c FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
        	}
        	    
        } else {
    		account = Util.globalAccount; 
    	}

       
       system.debug(account);
        	
        List<Schema.PicklistEntry> Types = Industry_Trend__c.Type__c.getDescribe().getPicklistValues();
        system.debug(Types);
    	trendsWrapperList = new List<TrendsWrapper>();
        Map<String, TrendsWrapper> trendsMap = new Map<String, TrendsWrapper>();
        Map<String, String> TypeValToLabel = new Map<String, String>();
        for (Schema.PicklistEntry pe : Types) {
            if(pe.getValue() != 'Soluciones') {
                TrendsWrapper tw = new TrendsWrapper(pe.getLabel());
    			trendsMap.put(pe.getLabel(), tw);
    			trendsWrapperList.add(tw);
            }
            TypeValToLabel.put(pe.getValue(), pe.getLabel());
        }
    	List<Id> regionsIds = Util.getParentsRegions(Util.getRegionFromAccount(account.Id, account.region__c));    	
    	
    	List<Industry_Trend__c> trendsX = new List<Industry_Trend__c>();
    	
    	
    	if(Schema.sObjectType.Industry_Trend__c.isAccessible() && Schema.sObjectType.Industry_Trend__c.fields.Region__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.LastModifiedDate.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.RelatedTo__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Trend__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.URL_Attachment__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.title__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.type__c.isAccessible()
    	){
    	
    	trendsX =[SELECT Region__c, Region__r.Name, LastModifiedDate, RelatedTo__c, RelatedTo__r.title__c, RelatedTo__r.Trend__c,
                           Name, Trend__c, URL_Attachment__c, title__c, type__c
                                       FROM Industry_Trend__c 
                                       WHERE Region__c in :regionsIds AND 
                                       		 (Sub_Sector__c = :account.Segmento_Vertical__c OR Sub_Sector__c = 'Todos' OR Sub_Sector__c = 'All') AND 
                                       		(Industry__c = :account.Micro_Industry__c OR Industry__c = 'Todos' OR Industry__c = 'All') AND
                                       		Type__c != 'Soluciones'
                                       ORDER BY Name ASC
                                       ];
    	}                             
    	
        for (Industry_Trend__c trend :trendsX) {
    		
           if(trendsMap.get(TypeValToLabel.get(trend.type__c)) != null){                               
               
               trendsMap.get(TypeValToLabel.get(trend.type__c)).trends.add(trend);
           }
    	}
        
        Solutions = new List<SolutionWrapper>();
        
        List<Industry_trend__c> solucionesX = new  List<Industry_trend__c>();
        
        if(Schema.sObjectType.Industry_Trend__c.isAccessible() && Schema.sObjectType.Industry_Trend__c.fields.Region__c.isAccessible()
         && Schema.sObjectType.Industry_Trend__c.fields.LastModifiedDate.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.RelatedTo__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Trend__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.URL_Attachment__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.title__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.type__c.isAccessible()
                ){
        
        solucionesX = [SELECT Region__c, Region__r.Name, LastModifiedDate, RelatedTo__c, RelatedTo__r.title__c, RelatedTo__r.Trend__c, RelatedTo__r.RelatedTo__r.title__c, RelatedTo__r.RelatedTo__r.Trend__c,
                           	Name, Trend__c, URL_Attachment__c, title__c, type__c, 
                                       		(SELECT 
                                             	name, Opportunity__c, Opportunity__r.name 
                                             FROM Opportunities__R  
                                             WHERE Opportunity__r.Account.id = :account.id AND 
                                             	Opportunity__r.stagename != 'Closed Won' AND 
                                             	Opportunity__r.stagename != 'Closed Lost') , 
                                       		(SELECT
                                             	Name, Current_state__c, Industry_Trend__c
                                             FROM Accounts_Industry_Trends__r
                                             WHERE Account__r.Id = :account.Id)
                                       	FROM Industry_Trend__c 
                                       	WHERE Region__c in :regionsIds AND 
                                       		(Sub_Sector__c = :account.Segmento_Vertical__c OR Sub_Sector__c = 'Todos' OR Sub_Sector__c = 'All') AND 
                                       		(Industry__c = :account.Micro_Industry__c OR Industry__c = 'Todos' OR Industry__c = 'All') AND
                                       		Type__c = 'Soluciones'
       									ORDER BY Name ASC];
        }							
        
        for(Industry_trend__c solution : solucionesX) {
            SolutionWrapper sw = new SolutionWrapper();
            if(solution.Accounts_Industry_Trends__r.size() == 0) {
                sw.Status = new Account_Industry_Trend__c(Industry_Trend__c = solution.Id, Account__c = account.Id);
            }
            else {
                sw.Status = solution.Accounts_Industry_Trends__r[0];
            }
            sw.Trend = solution;
            Solutions.add(sw);
        }
        SolutionsLabel = TypeValToLabel.get('Soluciones');
    }
    
    public PageReference save() {
        if(canEdit) {
            List<Account_Industry_Trend__c> acInTrs = new List<Account_Industry_Trend__c>();
            for(SolutionWrapper sw : Solutions) {
                acInTrs.add(sw.Status);
            }
            try {
                if(Schema.sObjectType.Account_Industry_Trend__c.isCreateable()
                && Schema.sObjectType.Account_Industry_Trend__c.fields.Industry_Trend__c.isCreateable()
                && Schema.sObjectType.Account_Industry_Trend__c.fields.Account__c.isCreateable()
                && Schema.sObjectType.Account_Industry_Trend__c.isUpdateable()
                && Schema.sObjectType.Account_Industry_Trend__c.fields.Industry_Trend__c.isUpdateable()
                && Schema.sObjectType.Account_Industry_Trend__c.fields.Account__c.isUpdateable())
                upsert acInTrs;
            } catch(DmlException ex){
                ApexPages.addMessages(ex);
            }
        }
        return null;
    }
    
    public PageReference ExportToExcel() {
    	return Page.accountIndustryTrendsExcel;
    	return null;
    }
 	
 	public String getExcelName() {
    	String name = account.Name + '-' + Label.Trend + '.xls';
    	return name.replaceAll(' ', '_').replaceAll(',','');
    }
	
    class SolutionWrapper {
        public Industry_Trend__c Trend {get; set;}
        public Account_Industry_Trend__c Status {get; set;}
    }
    
	class TrendsWrapper {
		
		public String type {get;set;}
        public String typeClass {get;set;}
		public List<Industry_Trend__c> trends {get;set;}
		
		public trendsWrapper(String t) {
			type = t;
            if (t == Label.Principales_players) {
                typeClass = 'Pla';
            } 
            
            if (t == Label.Tendencias) {
                typeClass = 'Ten';
            }
            
            if (t == Label.Casos_exito_sectorial) {
                typeClass = 'Cas';
            }
            
            if (t == Label.Metricas_analisis_mercado) {
                typeClass = 'Mét';
            }
            
            if (t == Label.Contexto_General) {
                typeClass = 'Con';
            }
            
            if (t == Label.Cadena_valor_procesos) {
                typeClass = 'Cad';
            }
            
            //else {
                //typeClass = t.substring(0, 3);
            //}
            
			trends = new List<Industry_Trend__c>();
		}
		
	}
	
}