src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>competitorName__c</fullName>
        <label>Nombre de la Competencia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isCompetitorContract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contrato con la Competencia</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_accountUpsellingOpportunitiesWNew.cls
@isTest 
public with sharing class test_accountUpsellingOpportunitiesWNew {

    static testMethod void myUnitTest() {
        
        Region__c r1=new Region__c();
        r1.Currency__c='aa';
        r1.Currency_Name__c='test';
        r1.Name='test1';
        insert r1;
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.industry = 'Banking';
        cuenta.Region__c=r1.Id;
        insert cuenta;
        
        Contract c = new Contract(accountId = cuenta.id, isCompetitorContract__c = false);
        insert c;
        
        Contract c1 = new Contract(accountId = cuenta.id, isCompetitorContract__c = true, competitorName__c = 'test');
        insert c1;
        
        System.currentPagereference().getParameters().put('id',cuenta.id);
        
        accountUpsellingOpportunitiesWindowNew p_Test = new accountUpsellingOpportunitiesWindowNew();
            
        p_Test.SaveChanges();
        
        system.assertEquals(1, p_Test.ourContracts.size());
        system.assertEquals(1, p_Test.competitorContracts.size());
        
    }
}