src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Account_Team_Member__c.object
<CustomObject>
    <label>SCP Account Team Member</label>
    <nameField>
        <label>Account Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Account Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Closest_Account_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Closest Account Team Member to this contact</description>
        <label>Closest Account Team Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Team_Member__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Team_Member__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contactos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact_Influence__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Influenced__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influenced</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences</relationshipLabel>
        <relationshipName>Contact_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Influences__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influences</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences (Contact Influence)</relationshipLabel>
        <relationshipName>Contact_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Influence</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Influence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Influences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_AccountContacts.cls
@isTest
private class test_AccountContacts {

    static testMethod void myUnitTest() {
        Region__c regionGlobal = new Region__C(name='Global');
        regionGlobal.Currency_Name__c ='asd';
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        regionLocal.Currency_Name__c ='asd';
        insert regionLocal;
        
        Account cuentaPadre =new Account();
        cuentaPadre.Name='testPadre';
        cuentaPadre.Region__c=regionGlobal.id;
        
        insert cuentaPadre;
        
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.parentId = cuentaPadre.id;
        
        insert cuenta;
        
        
        Contact contacto = new Contact();
        contacto.LastName = 'test';
        contacto.AccountId = cuenta.id;
        insert contacto;
        
        Contact contacto2 = new Contact();
        contacto2.LastName = 'test';
        contacto2.AccountId = cuenta.id;
        contacto2.ReportsToId = contacto.id;
        insert contacto2;
        
        Contact_Influence__c ci = new Contact_Influence__c();
        ci.Contact_Influenced__c = contacto.id;
        ci.Contact_Influences__c = contacto2.id;
        insert ci;
        
        
        System.currentPagereference().getParameters().put('id',cuenta.id);
        ApexPages.StandardController controllertest = new ApexPages.StandardController(cuenta);
        AccountContacts p_Test = new AccountContacts(controllertest);
        
        p_Test.getContacts();       
        
		List<Contact> temp = [SELECT Id, Name, ReportsToId,Closest_Account_Team_Member__r.name  FROM Contact WHERE AccountId = :cuenta.id];
        
        system.assertEquals(temp.size(),p_Test.contactList.size());
        
		AccountContacts p_Test2 = new AccountContacts();
		
		//DMLException
		Contact c = new Contact();
		p_Test2.getContacts();
		
		p_Test2.contactList.add(c);
		p_Test2.save();		

		
		p_Test2.goToNewContact();
		p_Test2.goToOrg();
		p_Test2.save();
		p_Test2.getExcelName();
		p_Test2.ExportToExcel();
        
    }
}