src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segmento_Vertical__c</fullName>
        <label>Segmento Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administración Pública, Defensa y Seguridad Social</fullName>
                </value>
                <value>
                    <fullName>Agricultura, Ganadería, Caza y Silvicultura</fullName>
                </value>
                <value>
                    <fullName>Asociaciones e Instituciones</fullName>
                </value>
                <value>
                    <fullName>Automotores - Autopartistas</fullName>
                </value>
                <value>
                    <fullName>Automotores - Concesionarios</fullName>
                </value>
                <value>
                    <fullName>Automotores - Industria Automotriz</fullName>
                </value>
                <value>
                    <fullName>Construcción</fullName>
                </value>
                <value>
                    <fullName>Consultoras</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Entretenimiento</fullName>
                </value>
                <value>
                    <fullName>Explotación de Minas y Canteras</fullName>
                </value>
                <value>
                    <fullName>Gobierno Extranjero</fullName>
                </value>
                <value>
                    <fullName>Gobierno Municipal</fullName>
                </value>
                <value>
                    <fullName>Gobierno Nacional</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Industria Alimenticia</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industrias - Otro</fullName>
                </value>
                <value>
                    <fullName>Logística</fullName>
                </value>
                <value>
                    <fullName>Manufactura</fullName>
                </value>
                <value>
                    <fullName>Medios de Comunicación</fullName>
                </value>
                <value>
                    <fullName>Petróleo</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Agua</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Correos</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Energía</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - GAS</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Transporte</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud - Clínicas, Sanatorios y Hospitales</fullName>
                </value>
                <value>
                    <fullName>Salud - Laboratorios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/AdministracionContextoSectorial__c.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>micro industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>segmento_vertical__c</fullName>
        <label>segmento vertical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administración Pública, Defensa y Seguridad Social</fullName>
                </value>
                <value>
                    <fullName>Agricultura, Ganadería, Caza y Silvicultura</fullName>
                </value>
                <value>
                    <fullName>Asociaciones e Instituciones</fullName>
                </value>
                <value>
                    <fullName>Automotores - Autopartistas</fullName>
                </value>
                <value>
                    <fullName>Automotores - Concesionarios</fullName>
                </value>
                <value>
                    <fullName>Automotores - Industria Automotriz</fullName>
                </value>
                <value>
                    <fullName>Construcción</fullName>
                </value>
                <value>
                    <fullName>Consultoras</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Entretenimiento</fullName>
                </value>
                <value>
                    <fullName>Explotación de Minas y Canteras</fullName>
                </value>
                <value>
                    <fullName>Gobierno Extranjero</fullName>
                </value>
                <value>
                    <fullName>Gobierno Municipal</fullName>
                </value>
                <value>
                    <fullName>Gobierno Nacional</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Industria Alimenticia</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industrias - Otro</fullName>
                </value>
                <value>
                    <fullName>Logística</fullName>
                </value>
                <value>
                    <fullName>Manufactura</fullName>
                </value>
                <value>
                    <fullName>Medios de Comunicación</fullName>
                </value>
                <value>
                    <fullName>Petróleo</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Agua</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Correos</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Energía</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - GAS</fullName>
                </value>
                <value>
                    <fullName>Prestadores Servicios Públicos - Transporte</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud - Clínicas, Sanatorios y Hospitales</fullName>
                </value>
                <value>
                    <fullName>Salud - Laboratorios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AdministracionContextoSectorial</label>
    <nameField>
        <label>Nombre de AdministracionContextoSectorial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdministracionContextoSectorial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contexto General</fullName>
                </value>
                <value>
                    <fullName>Métricas y Análisis del Mercado</fullName>
                </value>
                <value>
                    <fullName>Principales Players</fullName>
                </value>
                <value>
                    <fullName>Cadena de Valor y Procesos</fullName>
                </value>
                <value>
                    <fullName>Tendencias</fullName>
                </value>
                <value>
                    <fullName>Casos de éxito Sectorial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Attachment__c</fullName>
        <label>URL Attachment</label>
        <type>Url</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/adminIndustryTrends.cls
public with sharing class adminIndustryTrends {
    public String title { get; set; }

    public String regionId { get; set;}

    public String industry { get; set; }

    public String sector { get; set; }
    
    public Region__c region { get; set;}  
    
    private List<Industry_Trend__c> trends;
    
    public Industry_Trend__c newTrend { get; set; }
    
    public String IdtoDel {get; set;}

    public Boolean canEdit {get;set;}
    
    public AdministracionContextoSectorial__c tempAccount{get;set;}
    
    public adminIndustryTrends(){
    
        trends = new List<Industry_Trend__c>();
        title = 'Choose a Region and Industry to start';
        tempAccount = new AdministracionContextoSectorial__c();
        tempAccount.Micro_Industry__c = 'Todos';
        
        List<Region__c> regions = [SELECT Name,Id From Region__c where name = 'Global' ORDER BY id ASC limit 1];
        if(regions.size()>0){
            regionId = regions[0].id;    
        }
        
    }
	
    public void insertarRegionGlobal(){
        
        List<Region__c> regions = [SELECT Name,Id From Region__c where name = 'Global' ORDER BY id ASC limit 1];
        if(regions.size() == 0){
            
            Region__c regionglobal = new Region__c();
            regionglobal.name = 'Global';
            insert regionglobal;
            
            regionId = regionglobal.id;    
        }
    }
    public List<Industry_Trend__c> getTrends(){
        return trends;
    }
    

    public List<SelectOption> getRegions(){
        List<SelectOption> options = new List<SelectOption>();
        
        List<Region__c> temp = new List<Region__c>();
        
        if(Schema.sObjectType.Region__c.isAccessible() && Schema.sObjectType.Region__c.fields.Name.isAccessible() ){
        temp =  [SELECT Name,Id From Region__c ORDER BY id ASC limit 1000];
        }
        
       for( Region__c c : temp)
       {
          options.add(new SelectOption(c.Id,c.Name));
       }  
       return options;
        
    }
    
    public List<SelectOption> getSectors(){
        List<SelectOption> options = new List<SelectOption>();

            
       Schema.DescribeFieldResult fieldResult = Account.Sector__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
        
    }
    
    public List<SelectOption> getIndustries(){
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult = Account.segmento_vertical__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    public PageReference save(){
    	try {
    		Update trends;
    	} catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }    	
    	return null;
    }
    
    public void doUpdate(){
        
        region = [SELECT Id, Name, OwnerId FROM Region__c WHERE Id = :regionId];

        
        List<Region__Share> tempedit = new List<Region__Share>();
        
        if(Schema.sObjectType.Region__Share.isAccessible() ){
        tempedit = [select Id from Region__Share WHERE AccessLevel = 'Edit' AND ParentId =:regionId AND UserOrGroupId =:UserInfo.getUserId()];
        }
        if(tempedit.size() > 0 || region.OwnerId == UserInfo.getUserId())
            canEdit = true;
        else
            canEdit = false;
            
       
       	if (tempAccount.segmento_vertical__c == 'Todos') {
        	tempAccount.Micro_Industry__c = 'Todos';
        } else if ( tempAccount.Segmento_vertical__c == 'All') {
        	tempAccount.Micro_Industry__c = 'Todos';
        }
       	

        if(tempAccount.Segmento_vertical__c == 'All'){
            
            trends = [SELECT Trend__c,Name, type__c, URL_Attachment__c, title__c FROM Industry_Trend__c WHERE Region__c = :regionId];
        }else{
            
            trends = [SELECT Trend__c,Name, type__c, URL_Attachment__c, title__c FROM Industry_Trend__c 
                      WHERE Region__c = :regionId AND Industry__c = :tempAccount.Micro_Industry__c AND /*Sector__C = :tempAccount.Sector__c AND*/ 
                      Sub_Sector__c = :tempAccount.segmento_vertical__c ORDER BY Name ASC];
            
            system.debug(tempAccount.Micro_Industry__c);
            system.debug(trends);
        }
        
        newTrend = new Industry_Trend__c();
        if (Schema.sObjectType.Industry_Trend__c.fields.Region__c.isCreateable()){
            newTrend.Region__c = regionId;}
        if (Schema.sObjectType.Industry_Trend__c.fields.Industry__c.isCreateable()){
            newTrend.Industry__c = tempAccount.Micro_Industry__c;}
        if (Schema.sObjectType.Industry_Trend__c.fields.Sub_Sector__c.isCreateable()){
            newTrend.Sub_Sector__c = tempAccount.segmento_vertical__c;}
        /*newTrend.Sector__C = tempAccount.Sector__c;*/
        title = region.Name + ' > '+tempAccount.segmento_vertical__c+' > '  + tempAccount.Micro_Industry__c;
                
        if(tempAccount.Micro_Industry__c == '' || tempAccount.segmento_vertical__c == '' || 
           tempAccount.Micro_Industry__c == '--None--' || tempAccount.segmento_vertical__c == '--None--' || 
           tempAccount.Micro_Industry__c == null || tempAccount.segmento_vertical__c == null){
            tempAccount.segmento_vertical__c=null;
            canEdit = false;
            title = 'Debe seleccionar un Sector y un Subsector';
        }
    
    }
    

    public PageReference InsertNewTrend() {
        if(newTrend.Trend__C != null) {
            try {
            	
                if (Schema.sObjectType.Industry_Trend__c.isCreateable()){
                    insert newTrend;
                }
                
            } catch(DmlException ex){
	        	ApexPages.addMessages(ex);
	    	}
        }
        this.doUpdate();
        return null;
    }


    public PageReference del(){
    
        //this.IdtoDel = Apexpages.currentPage().getParameters().get('IdtoDelete');  
        
        Industry_Trend__c toDel = new Industry_Trend__c();
        
        if(Schema.sObjectType.Industry_Trend__c.isAccessible()){
        toDel= [ SELECT id FROM Industry_Trend__c WHERE Id = :this.IdtoDel];
        }
        
        try {
        	if(Industry_Trend__c.sObjectType.getDescribe().isDeletable()){
                delete toDel;
            }
        } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
        
        doUpdate();
        
        return null;       
    }

    public String getHashIndustry(){
        if(tempAccount.Micro_Industry__c !=null)
            return tempAccount.Micro_Industry__c.replaceAll('[^a-zA-Z]', '');
        else
            return '*';
    }
    


}