src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Criteria_Last_Update__c</fullName>
        <label>Política de Compras Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Buying_Criteria__c</fullName>
        <label>Política de Compras</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descripcion_del_Cliente_New__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Descripciones del cliente</relationshipLabel>
        <relationshipName>Descripciones_del_cliente1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estrategico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Descripcion del Cliente New</label>
    <nameField>
        <label>Nombre de Descripcion del Cliente 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descripciones del cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accountStrategicContextWindowTest.cls
@isTest
public class accountStrategicContextWindowTest {

    static testMethod void test1(){
        
            
        Account cuenta2 = new Account();
        cuenta2.name = 'CuentaPrueba';
        cuenta2.Strategic_Context__c = 'dasdasdasas';
        cuenta2.Buying_Criteria__c = 'dasdasbdgdgbvbv';
        insert cuenta2;
        
        Strategic_Initiative__c strategy = new Strategic_Initiative__c();
        //strategy.name = 'estrategia';
        strategy.Account__c = cuenta2.id;
        insert strategy;
        
        
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        cuenta.Strategic_Context__c = 'arnoezio';
        cuenta.Buying_Criteria__c = 'rogueonetoday';
        cuenta.ParentId = cuenta2.id;
        insert cuenta;
        
        Strategic_Initiative__c strategy2 = new Strategic_Initiative__c();
        //strategy.name = 'estrategia';
        strategy2.Account__c = cuenta.id;
        insert strategy2;
        
        Descripcion_del_cliente_New__c descr = new Descripcion_del_cliente_New__c();
        descr.name = 'desc';
        //descr.Cuenta__c = cuenta.id;
        //insert descr;
        
        Account_Competitor__c competidor = new Account_Competitor__c();
        competidor.name = 'comp';
        competidor.Account__c = cuenta.id;
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        AccountStrategicContextWindow controller = new accountStrategicContextWindow();
        
        controller.insertarData();
        
        controller.account = cuenta;
        
        controller.InsertIniciative();
        
        system.assertEquals(2, controller.localStrategicInitiatives.size());
        
        controller.delid = strategy2.id;
        controller.DeleteStrategicInitiatives();
        
        system.assertEquals(1, controller.localStrategicInitiatives.size());
        
        cuenta.Strategic_Context__c = 'dasda4353454354';
        cuenta.Buying_Criteria__c = 'lalalalalalal';
        controller.SaveChanges();
        
		controller.getExcelName();
		controller.ExportToExcel(); 
        
        controller.newCompetitor = competidor;
        controller.add();
        
        controller.InsertCompetitor();
        
        //system.assertEquals(2, controller.newCompetitors.size());
        
        controller.delid = competidor.id;
        controller.DeleteCompetitor();

		system.assertEquals(1, controller.newCompetitors.size());

		controller.borra();
		controller.borra2();

		system.assertEquals(null, controller.account.Buying_Criteria__c);
        system.assertEquals(null, controller.account.Buying_Criteria_Last_Update__c);
    }
    
}