src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand_Strengths__c</fullName>
        <label>Brand Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fact__c</fullName>
        <label>Fact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_accountOverallRelationshipWindow.cls
@isTest
private class test_accountOverallRelationshipWindow {

    static testMethod void myUnitTest() {
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
        
        Account cuentaPadre =new Account();
        cuentaPadre.Name='testPadre';
        cuentaPadre.Region__c=regionGlobal.id;
      
      	insert cuentaPadre;
      
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.parentId = cuentaPadre.id;
        cuenta.industry = 'Banking';
        
        insert cuenta;
        
        System.currentPagereference().getParameters().put('id',cuenta.id);
        
	    accountOverallRelationshipWindow p_Test = new accountOverallRelationshipWindow();
	    
	    p_Test.account.Brand_Strengths__c = 'Test';  
	    
	    p_Test.InsertCompetitor();
	    p_Test.newCompetitors.get(0).Name = 'Test';
	    p_Test.newCompetitors.get(0).Fact__c = 'Fact';
	    
	    p_Test.SaveChanges();
	    
	    Account accResult = [select id,Brand_Strengths__c from Account where id = :cuenta.id];
	    system.assertEquals('Test', accResult.Brand_Strengths__c);
	    
	    List<Account_Competitor__c> accCompList = [select id, Name, Fact__c from Account_Competitor__c where account__c = :cuenta.id]; 
	    system.assertEquals(1, accCompList.size());
	    
	    p_Test.add();
	    
	    List<Account_Competitor__c> accCompList2 = [select id, Name, Fact__c from Account_Competitor__c where account__c = :cuenta.id]; 
	    system.assertEquals(2, accCompList2.size());
	    
	    p_Test.delid = accCompList.get(0).id;
	    p_Test.DeleteCompetitor();
	    
	    List<Account_Competitor__c> accCompList3 = [select id, Name, Fact__c from Account_Competitor__c where account__c = :cuenta.id]; 
	    system.assertEquals(1, accCompList3.size());
	    
	    //Test DmlException
	    p_Test.newCompetitor = accCompList3.get(0);
	    p_Test.add();
	    system.assert(ApexPages.hasMessages());
	    
  }
}