src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Casos de exito en la cuenta</fullName>
                </value>
                <value>
                    <fullName>Diferenciadores competitivos en la cuenta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_AccountPastProvenValueNewController.cls
@isTest
private class Test_AccountPastProvenValueNewController {

	static testMethod void myUnitTest() {
		

		/* Create Region */
		Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__C(name='Latam', parent__c = regionGlobal.id);
        insert regionLocal;
		
		/* Create Account */
		String accountName = 'Account Test';
		Account acctParent = new Account(Name=accountName);
		insert acctParent;		
				
		Account acct = new Account(Name=accountName, Region__c=regionLocal.id, parentId = acctParent.id);
		insert acct;
		
		List<Account> acctResult = [select id from Account where name = :accountName];
		system.Assert(acctResult.size()>0, 'Error to create Account: ' + acct);
		
		String description = 'Update Descr';
		PastProvenValueNew__c ppvNew = new PastProvenValueNew__c(Unique_Value__c = description, account__c = acctParent.id);
		
		/* Set Page and Create Controller*/
		System.currentPagereference().getParameters().put('id',acct.id);
		AccountPastProvenValueNewController controller = new AccountPastProvenValueNewController();
		
		controller.add();
		List<PastProvenValueNew__c> ppvList = [select id from PastProvenValueNew__c where account__c = :acct.id]; 
		system.assert(ppvList.size() == 1);
						
		controller.pastProvenValueNewList.get(0).Unique_Value__c = description;
		controller.pastProvenValueNewList.get(0).type__c = 'Account Success Stories';
		controller.save();
		
		List<PastProvenValueNew__c> ppvList2 = [select id, Unique_Value__c from PastProvenValueNew__c where account__c = :acct.id];				
		system.assertEquals(description,ppvList2.get(0).Unique_Value__c);		
		
		AccountPastProvenValueNewController controller2 = new AccountPastProvenValueNewController();
		controller2.toDel = controller2.pastProvenValueNewList.get(0).id;
		
		controller2.del();
		List<PastProvenValueNew__c> ppvList3 = [select id from PastProvenValueNew__c where account__c = :acct.id];				
		system.assert(ppvList3.size()==0);
		
		controller2.getExcelName();
		controller2.ExportToExcel();
		
	}

}