src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>competitorName__c</fullName>
        <label>Nombre de la Competencia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fcv__c</fullName>
        <label>Valor Total del Contrato</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isCompetitorContract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contrato con la Competencia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>mrc__c</fullName>
        <label>Cargo Recurrente Mensual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/accountUpsellingOpportunitiesWindowNew.cls
public with sharing class accountUpsellingOpportunitiesWindowNew {
    
    public Account account { get; set; }
    public Date now {get; set;}
    public Boolean canEdit {get;set;}
    public List<Contract> ourContracts {get;set;}
    public List<Contract> competitorContracts {get;set;} 
    
    public accountUpsellingOpportunitiesWindowNew() {
        this.now = Date.today();
        
        if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible()
        && Schema.sObjectType.Account.fields.parentId.isAccessible()
        && Schema.sObjectType.Account.fields.Industry.isAccessible()
        && Schema.sObjectType.Account.fields.Region__c.isAccessible()
        ){
        this.account = [SELECT name, id, parentId, Industry, Region__c, Region__r.Currency__c, Region__r.Currency_Name__c FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
        }
        ourContracts = new List<Contract>();
        competitorContracts = new List<Contract>(); 
        
        if(Schema.sObjectType.Contract.fields.ContractNumber.isAccessible()
        && Schema.sObjectType.Contract.fields.description.isAccessible()
        && Schema.sObjectType.Contract.fields.StartDate.isAccessible()
        && Schema.sObjectType.Contract.fields.ContractTerm.isAccessible()
        && Schema.sObjectType.Contract.fields.EndDate.isAccessible()
        && Schema.sObjectType.Contract.fields.mrc__c.isAccessible()
        && Schema.sObjectType.Contract.fields.fcv__c.isAccessible()
        && Schema.sObjectType.Contract.fields.competitorName__c.isAccessible()
        && Schema.sObjectType.Contract.fields.isCompetitorContract__c.isAccessible()
        && Schema.sObjectType.Contract.isAccessible()){
        
        List<Contract> contrects = new List<Contract>();
        
        if(Schema.sObjectType.Contract.isAccessible() && Schema.sObjectType.Contract.fields.ContractNumber.isAccessible()
        && Schema.sObjectType.Contract.fields.description.isAccessible()
        && Schema.sObjectType.Contract.fields.StartDate.isAccessible()
        && Schema.sObjectType.Contract.fields.ContractTerm.isAccessible()
        && Schema.sObjectType.Contract.fields.EndDate.isAccessible()
        && Schema.sObjectType.Contract.fields.mrc__c.isAccessible()
        && Schema.sObjectType.Contract.fields.fcv__c.isAccessible()
        && Schema.sObjectType.Contract.fields.competitorName__c.isAccessible()
        && Schema.sObjectType.Contract.fields.isCompetitorContract__c.isAccessible()
        ){
        contrects = [select id, ContractNumber, description, StartDate, ContractTerm, EndDate, mrc__c, fcv__c, competitorName__c, isCompetitorContract__c from Contract where accountid = :account.id];
        }
        
        for (Contract c :contrects) {
            if (!c.isCompetitorContract__c) {
                ourContracts.add(c);
            } else {
                competitorContracts.add(c);
            }               
        }       
        }
        
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);
    }
    
    public PageReference SaveChanges() {
        
        if(Schema.sObjectType.Contract.fields.ContractNumber.isUpdateable()
        && Schema.sObjectType.Contract.fields.description.isUpdateable()
        && Schema.sObjectType.Contract.fields.StartDate.isUpdateable()
        && Schema.sObjectType.Contract.fields.ContractTerm.isUpdateable()
        && Schema.sObjectType.Contract.fields.EndDate.isUpdateable()
        && Schema.sObjectType.Contract.fields.mrc__c.isUpdateable()
        && Schema.sObjectType.Contract.fields.fcv__c.isUpdateable()
        && Schema.sObjectType.Contract.fields.competitorName__c.isUpdateable()
        && Schema.sObjectType.Contract.fields.isCompetitorContract__c.isUpdateable()
        && Schema.sObjectType.Contract.isUpdateable()){
            update ourContracts;
            update competitorContracts;
        }
        return null;
    }
}