src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Big_Deal__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Big Deals</relationshipLabel>
        <relationshipName>Big_Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>currency1__c</fullName>
        <label>FCV o Valor total del Contrato</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>currency2__c</fullName>
        <label>NAV o ingresos próximos 12 meses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>date1__c</fullName>
        <label>¿Cuándo hay que entregar la oferta?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>date2__c</fullName>
        <label>Fecha estimada de comienzo del contrato</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>number1__c</fullName>
        <label>Duración del proyecto (meses)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>number2__c</fullName>
        <label>¿Cuál es el plazo de ejecución (meses)?</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>number3__c</fullName>
        <label>Nº de meses hasta entregar la propuesta</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>question1__c</fullName>
        <label>question1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question2__c</fullName>
        <label>question2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question3__c</fullName>
        <label>question3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question4__c</fullName>
        <label>question4</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question5__c</fullName>
        <label>question5</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question6__c</fullName>
        <label>question6</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question7__c</fullName>
        <label>question7</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>question8__c</fullName>
        <label>question8</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Big Deal</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Big Deal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contexto General</fullName>
                </value>
                <value>
                    <fullName>Métricas y Análisis del Mercado</fullName>
                </value>
                <value>
                    <fullName>Principales Players</fullName>
                </value>
                <value>
                    <fullName>Cadena de Valor y Procesos</fullName>
                </value>
                <value>
                    <fullName>Tendencias</fullName>
                </value>
                <value>
                    <fullName>Casos de éxito Sectorial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PastProvenValueNew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Past Proven Value</label>
        <referenceTo>PastProvenValueNew__c</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Opportunity - PastProvenValueNew</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityPastProvenValueNew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Opportunity - PastProvenValueNew</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Project/Capability Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Titulo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Casos de exito en la cuenta</fullName>
                </value>
                <value>
                    <fullName>Diferenciadores competitivos en la cuenta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Titulo</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunitySnapshotController.cls
public with sharing class OpportunitySnapshotController {
	
	public Opportunity opp {get;set;}
	public List<valueArguments> valueArgumentsList {get;set;}
    public List<valueArguments> solutionsList {get;set;}
	public List<Task> taskList {get;set;}
	public String isoCode {get;set;}
	public Decimal fcv {get;set;}
	public Integer chartSum {get;set;}
	public List<PieWedgeData> pieData {get;set;}
	
	/*
	public List<OportunityIndustryTrend__c> trendList {get;set;}
	public List<OpportunityStrategicInitiative__c> strategicList {get;set;}
	public List<OpportunityPastProvenValueNew__c> pastPtovenValueList {get;set;} 
	*/
	
	public OpportunitySnapshotController(ApexPages.StandardController controller) {        
        opp = (Opportunity)controller.getRecord();
        if (Util.checkMultiCurrencyEnabled()) {
        	isoCode = UserInfo.getDefaultCurrency()+' ';
        	
        	if(Schema.sObjectType.Opportunity.isAccessible()){
        	fcv = [select convertCurrency(amount) from Opportunity where id = :opp.id limit 1].get(0).amount;
        	}
        } else {
        	isoCode = '$';
        	if(Schema.sObjectType.Opportunity.isAccessible()
        	&& Schema.sObjectType.Opportunity.fields.amount.isAccessible()){
        	fcv = fcv = [select amount from Opportunity where id = :opp.id limit 1].get(0).amount;
        	}
        }   
        init();        
    }
    
    private void init() {		
		/*
		trendList = [select Industry_Trend__c, Industry_Trend__r.Name, Industry_Trend__r.Trend__c from OportunityIndustryTrend__c where Opportunity__c = :opp.id];			
		strategicList = [select Strategic_Initiative__c, Strategic_Initiative__r.Name, Strategic_Initiative__r.Strategic_Initiative__c from OpportunityStrategicInitiative__c where Opportunity__c = :opp.id];  
		pastPtovenValueList = [select PastProvenValueNew__c, PastProvenValueNew__r.Name, PastProvenValueNew__r.Unique_Value__c from OpportunityPastProvenValueNew__c where Opportunity__c = :opp.id]; 	
    	*/
    	valueArgumentsList = new List<valueArguments>();
    	
    	if(Schema.sObjectType.OportunityIndustryTrend__c.isAccessible()
    	&& Schema.sObjectType.OportunityIndustryTrend__c.fields.Industry_Trend__c.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.Industry_Trend__c.fields.Trend__c.isAccessible()){
    	for (OportunityIndustryTrend__c trend :[select Industry_Trend__c, Industry_Trend__r.Name, Industry_Trend__r.Trend__c from OportunityIndustryTrend__c where Opportunity__c = :opp.id  and Industry_Trend__r.type__c != 'Soluciones']) {
    		valueArgumentsList.add(new valueArguments(trend.Industry_Trend__r.Name, trend.Industry_Trend__r.Trend__c, Label.Trend));
    	}
    	}
    	
    	if(Schema.sObjectType.OpportunityStrategicInitiative__c.isAccessible()
    	&& Schema.sObjectType.OpportunityStrategicInitiative__c.fields.Strategic_Initiative__c.isAccessible()
    	&& Schema.sObjectType.Strategic_Initiative__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.Strategic_Initiative__c.fields.Strategic_Initiative__c.isAccessible()){
    	    
    	for (OpportunityStrategicInitiative__c strategic :[select Strategic_Initiative__c, Strategic_Initiative__r.Name, Strategic_Initiative__r.Strategic_Initiative__c from OpportunityStrategicInitiative__c where Opportunity__c = :opp.id]) {
    		valueArgumentsList.add(new valueArguments(strategic.Strategic_Initiative__r.Name, strategic.Strategic_Initiative__r.Strategic_Initiative__c, Label.Iniciativa));
    	}
    	}
    	
    	if(Schema.sObjectType.OpportunityPastProvenValueNew__c.isAccessible()
    	&& Schema.sObjectType.OpportunityPastProvenValueNew__c.fields.PastProvenValueNew__c.isAccessible()
    	&& Schema.sObjectType.PastProvenValueNew__c.fields.Name.isAccessible()
    	&& Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isAccessible()
    	&& Schema.sObjectType.PastProvenValueNew__c.fields.Type__c.isAccessible()){
    	    
    	for (OpportunityPastProvenValueNew__c ppv :[select PastProvenValueNew__c, PastProvenValueNew__r.Name, PastProvenValueNew__r.Unique_Value__c, PastProvenValueNew__r.Type__c from OpportunityPastProvenValueNew__c where Opportunity__c = :opp.id]) {
    		valueArgumentsList.add(new valueArguments(ppv.PastProvenValueNew__r.Name, ppv.PastProvenValueNew__r.Unique_Value__c, ppv.PastProvenValueNew__r.Type__c));
    	}
    	}
    	
    	
        solutionsList = new List<valueArguments>();
        if(Schema.sObjectType.OportunityIndustryTrend__c.isAccessible()
        && Schema.sObjectType.OportunityIndustryTrend__c.fields.Industry_Trend__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.title__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.type__c.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Name.isAccessible()
        && Schema.sObjectType.Industry_Trend__c.fields.Trend__c.isAccessible()){
            
        for (OportunityIndustryTrend__c trend :[select Industry_Trend__c, Industry_Trend__r.title__c, Industry_Trend__r.type__c, Industry_Trend__r.Name, Industry_Trend__r.Trend__c from OportunityIndustryTrend__c where Opportunity__c = :opp.id and Industry_Trend__r.type__c = 'Soluciones']) {
            solutionsList.add(new valueArguments(trend.Industry_Trend__r.Name, trend.Industry_Trend__r.title__c, trend.Industry_Trend__r.trend__c));
        }
        }
    	/*
    	for (OpportunityStrategicContext__c strategicCont :[select Account__c, Account__r.Id, Account__r.Strategic_Context__c from OpportunityStrategicContext__c where Opportunity__c = :opp.id]) {
    		valueArgumentsList.add(new valueArguments(strategicCont.Account__r.Id, strategicCont.Account__r.Strategic_Context__c, 'Strategic Context'));
    	}
    	*/
    	
    	if(Schema.sObjectType.Task.isAccessible()
    	&& Schema.sObjectType.Task.fields.subject.isAccessible()
    	&& Schema.sObjectType.Task.fields.Description.isAccessible()
    	&& Schema.sObjectType.Task.fields.ActivityDate.isAccessible()
    	&& Schema.sObjectType.Task.fields.Status.isAccessible()
    	&& Schema.sObjectType.Task.fields.Priority.isAccessible()
    	&& Schema.sObjectType.Task.fields.End_date__c.isAccessible()
    	&& Schema.sObjectType.Task.fields.OwnerId.isAccessible()
    	&& Schema.sObjectType.Task.fields.CreatedDate.isAccessible()
    	&& Schema.sObjectType.Task.fields.URL__C.isAccessible()){
    	    
            system.debug('entre');
    	taskList = [select subject, Description, ActivityDate, Status,Priority,End_date__c, 
    	            OwnerId, CreatedDate, Owner.Name, URL__C FROM Task WHERE WhatId = :opp.id];
    	}
    	
    	generatePieData();
    }
	
	public PageReference save() {
	    
	    if(Schema.sObjectType.Opportunity.isUpdateable())
		update opp;
		return null;		
	}
	
	public PageReference saveTask() {
        
        if(Schema.sObjectType.Task.isUpdateable()
           && Schema.sObjectType.Task.fields.subject.isUpdateable()
           && Schema.sObjectType.Task.fields.Description.isUpdateable()
           && Schema.sObjectType.Task.fields.ActivityDate.isUpdateable()
           && Schema.sObjectType.Task.fields.Status.isUpdateable()
           && Schema.sObjectType.Task.fields.Priority.isUpdateable()
           && Schema.sObjectType.Task.fields.End_date__c.isUpdateable()
           && Schema.sObjectType.Task.fields.OwnerId.isUpdateable()
           && Schema.sObjectType.Task.fields.URL__C.isUpdateable()){
               system.debug('entre');
               update taskList;
           }
        
		return null;		
	}
	
	class valueArguments {
		
		public String id {get;set;}
		public String argument {get;set;}
		public String argType {get;set;}
		
		public valueArguments(String i, String arg, String argT) {
			id = i;
			argument = arg;
			argType = argT;
		}
		
	}
	
	private void generatePieData() {  
        
        pieData = new List<PieWedgeData>();
        
        if(Schema.sObjectType.Big_Deal__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question1__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question2__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question3__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question4__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question5__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question6__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question7__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.question8__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.date1__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.date2__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.currency1__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.currency2__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.number1__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.number2__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.number3__c.isAccessible()
        && Schema.sObjectType.Big_Deal__c.fields.number4__c.isAccessible()){
            
        for(Big_Deal__c bd :[select id, question1__c, question2__c, 
        question3__c, question4__c, question5__c, question6__c, question7__c, question8__c, 
        date1__c, date2__c, currency1__c, currency2__c, number1__c, number2__c, number3__c, number4__c from Big_Deal__c where opportunity__c = :opp.id]) {           
            
            Integer calendar = 0;
            if (bd.date1__c != null) {
            	calendar += 10;
            }
            if (bd.date2__c != null) {
            	calendar += 10;
            }
            
            Integer economic = 0;
            if (bd.currency1__c != null) {
            	economic += 10;
            }
            if (bd.currency2__c != null) {
            	economic += 10;
            }
            
            Integer alc = 0;
            if (bd.number1__c != null) {
            	alc += 10;
            }
            if (bd.number2__c != null) {
            	alc += 10;
            }
            
            Integer prev = 0;
            if (bd.number3__c != null) {
            	prev += 10;
            }
            if (bd.number4__c != null) {
            	prev += 10;
            }
            
            Integer rie = 0;
            if (bd.question1__c != null) {
            	rie += 10;
            }
            if (bd.question2__c != null) {
            	rie += 10;
            }
            
            chartSum = calendar + economic + alc + prev + rie;
            integer chartTotal = 10;
            
            //pieData.add(new PieWedgeData('Empty',chartTotal - chartSum));
            pieData.add(new PieWedgeData('Calendario',calendar));
            pieData.add(new PieWedgeData('Datos Económicos',economic));
            pieData.add(new PieWedgeData('Alcance',alc));
            pieData.add(new PieWedgeData('Preventa y Oferta',prev));
            pieData.add(new PieWedgeData('Riesgos',rie));
        }
        }
            
        }  
    
    // Wrapper class  
    public class PieWedgeData 
    {  
        public String name { get; set; }  
        public Integer data { get; set; }  
        
        public PieWedgeData(String name, Integer data) {  
              
            if (data != null) {
            	this.data = data;
            } else {
            	this.data = 0;
            } 
            this.name = name;
        }  
    } 
	
}