src/objects/AccountKPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountsKPI</relationshipLabel>
        <relationshipName>AccountsKPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <referenceTo>KPI__c</referenceTo>
        <relationshipLabel>AccountsKPI</relationshipLabel>
        <relationshipName>AccountsKPI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AccountKPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de AccountKPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountsKPI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <recordTypes>
        <fullName>KPI</fullName>
        <active>true</active>
        <label>KPI</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExtendedKPI.cls
public with sharing class ExtendedKPI{

    public AccountKPI__c thisyear {get;set;}
    public AccountKPI__c lastyear {get;set;}
    public AccountKPI__c last2year {get;set;}
    public AccountKPI__c last3year {get;set;}
    public KPI__c kpi {get;set;}
    public String source {get;set;}
	
	public ExtendedKPI(KPI__C kpi,List<AccountKPI__C> kpisData,Integer year,String AccountId, String source){
		this(kpi,kpisData,year,AccountId);	
		this.source = source.replace('Todos - Todos', 'Todos').replace('All - All', 'All');
	}
	
    public ExtendedKPI(KPI__C kpi,List<AccountKPI__C> kpisData,Integer year,String AccountId){
    
        this.kpi = kpi;
        
        for(AccountKPI__C k : kpisData){
        
            if(k.KPI__R.id == kpi.id){
            
                if(k.Year__c == year)
                    thisyear = k;
                else if(k.Year__c == (year-1))
                    lastyear = k;
                else if(k.Year__c == (year-2))
                    last2year = k;
                else if(k.Year__c == (year-3))
                    last3year = k;    
            
            }
        
        }
        
        if(thisyear==null)
            thisyear = new AccountKPI__c(Account__c = AccountId, KPI__c = kpi.id, Year__c = year); 
        if(lastyear==null)
            lastyear = new AccountKPI__c(Account__c = AccountId, KPI__c = kpi.id, Year__c = (year-1)); 
        if(last2year==null)
            last2year = new AccountKPI__c(Account__c = AccountId, KPI__c = kpi.id, Year__c = (year-2));
        if(last3year==null)
            last3year = new AccountKPI__c(Account__c = AccountId, KPI__c = kpi.id, Year__c = (year-3));
    
    }


    public void save(){
    
        if(thisyear.id == null)
            if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isCreateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.isCreateable())
            insert thisyear;
        else
                    if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isUpdateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.isUpdateable())
            update thisyear;    
            
            
        if(lastyear.id == null)
                    if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isCreateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.isCreateable())
            insert lastyear;
        else
                            if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isUpdateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.isUpdateable())
            update lastyear;   
             
             
        if(last2year.id == null)
                    if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isCreateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.isCreateable())
            insert last2year;
        else
                            if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isUpdateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.isUpdateable())
            update last2year;
            
        if(last3year.id == null)
                    if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isCreateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isCreateable() &&
                Schema.sObjectType.AccountKPI__c.isCreateable())
            insert last3year;
        else
                            if(Schema.sObjectType.AccountKPI__c.fields.Account__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.fields.KPI__c.isUpdateable() && 
                Schema.sObjectType.AccountKPI__c.fields.Year__c.isUpdateable() &&
                Schema.sObjectType.AccountKPI__c.isUpdateable())
            update last3year;
    
    }
}