src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CUIT__c</fullName>
        <label>CUIT</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>idClienteLegado__c</fullName>
        <label>Id Cliente Legado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estado_de_la_oportunidad__c</fullName>
        <label>Estado de la oportunidad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En Curso</fullName>
                </value>
                <value>
                    <fullName>Perdida</fullName>
                </value>
                <value>
                    <fullName>Firmado</fullName>
                </value>
                <value>
                    <fullName>Instalado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/IFS_S419_getOpportunities.cls
global class IFS_S419_getOpportunities {
    
    webservice static wrapperResponse getOpportunities(String cuit_Req, String idClienteLegado){
        
        if(cuit_Req == null || idClienteLegado == null){
            throw new serviceSoapException('Los campos cuit_Req e idClienteLegado son obligatorios');
        }
        
        wrapperResponse response = new wrapperResponse();
        List<Account> cuentas = new List<Account>();
        Decimal cuit = Decimal.valueOf(cuit_Req);
        List<Opportunity> oportunidades = new List<Opportunity>();
        cuentas = [select id, cuit__c from Account where cuit__c =: cuit and idClienteLegado__c =: idClienteLegado limit 1];
        if(cuentas.size()>0){
            Id cuenta_ID = cuentas[0].id;
            oportunidades = [select id, Account.id, name, Estado_de_la_oportunidad__c from Opportunity where Account.id =: cuenta_ID and Account.idClienteLegado__c =: idClienteLegado];
            if(oportunidades.size()<1){
                response.codError='02';
                response.descError = 'No hay oportunidades para ese cliente';
            }else{
                for(Opportunity op : oportunidades){
                    wrapperOportunidades wop =  new wrapperOportunidades();
                    wop.Id_op=op.id;
                    wop.Description_op=op.name;
                    wop.estado_oportunidad=op.Estado_de_la_oportunidad__c;
                    response.listaOportunidades.add(wop);
                }
                response.codError='00';
                response.descError = 'OK';
            }    
        } else {
            response.codError='03';
            response.descError = 'Cliente inexistente';
        }
        return response;
    }
    
    global class wrapperResponse{
        webservice List<wrapperOportunidades> listaOportunidades;
        webservice String codError;
        webservice String descError;
        
        public wrapperResponse(){
           listaOportunidades = new List<wrapperOportunidades>();
        }
    }
    
    global class wrapperOportunidades{
        webservice String Id_op;
        webservice String Description_op;
        webservice String estado_oportunidad;
    }
}