src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand_Opportunities__c</fullName>
        <label>Brand Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Strengths__c</fullName>
        <label>Brand Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Threats__c</fullName>
        <label>Brand Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Weakness__c</fullName>
        <label>Brand Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Buying_Criteria_Last_Update__c</fullName>
        <label>Política de Compras Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Buying_Criteria__c</fullName>
        <label>Política de Compras</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSAT_Current_Year__c</fullName>
        <label>CSAT Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Last_Year__c</fullName>
        <label>CSAT Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Second_To_Last_Year__c</fullName>
        <label>CSAT Second To Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Unit__c</fullName>
        <label>CSAT Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Opportunities__c</fullName>
        <label>Other Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Strengths__c</fullName>
        <label>Other Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Threats__c</fullName>
        <label>Other Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Weakness__c</fullName>
        <label>Other Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Opportunities__c</fullName>
        <label>People Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Strengths__c</fullName>
        <label>People Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Threats__c</fullName>
        <label>People Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Weakness__c</fullName>
        <label>People Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Opportunities__c</fullName>
        <label>Products/Services Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Strengths__c</fullName>
        <label>Products/Services Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Threats__c</fullName>
        <label>Products/Services Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Weakness__c</fullName>
        <label>Products/Services Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fact__c</fullName>
        <label>Fact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descripcion_del_Cliente_New__c.object
<CustomObject>
    <fields>
        <fullName>CSAT_Current_Year__c</fullName>
        <label>CSAT Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Last_Year__c</fullName>
        <label>CSAT Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Second_To_Last_Year__c</fullName>
        <label>CSAT Second To Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Unit__c</fullName>
        <label>CSAT Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cantidad_de_edificios__c</fullName>
        <label>Cantidad de Edificios</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Descripciones del cliente</relationshipLabel>
        <relationshipName>Descripciones_del_cliente1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>El_n_mero_de_sucursales_crece_decrece__c</fullName>
        <label>Numero de sucursales crece decrece</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Crece</fullName>
                </value>
                <value>
                    <fullName>Se mantiene</fullName>
                </value>
                <value>
                    <fullName>Decrece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parque_Automotor_Propio_o_Gestionado__c</fullName>
        <label>Parque Automotor Propio Gestionado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Propio</fullName>
                </value>
                <value>
                    <fullName>Gestionado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Presupuesto_anual_que_maneja_tu_cliente__c</fullName>
        <label>Presupuesto Anual del Cliente</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualizacion</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estrategico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cantidad_de_empleados__c</fullName>
        <label>Cantidad de Empleados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cantidad_de_sucursales__c</fullName>
        <label>Cantidad de Sucursales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dispone_de_parque_automotor__c</fullName>
        <label>Dispone de Parque Automotor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>siguientes_pa_ses_tienen_negocio__c</fullName>
        <label>Que paises tienen negocio</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>España</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Myanmar</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>veh_culos_dispone_el_parque__c</fullName>
        <label>Cuantos Vehiculos Dispone el Parque</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Descripcion del Cliente New</label>
    <nameField>
        <label>Nombre de Descripcion del Cliente 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descripciones del cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accountStrategicContextWindow.cls
public with sharing class accountStrategicContextWindow {
    
    public List<Strategic_Initiative__c>  localStrategicInitiatives { get; set; }
    
    public List<Strategic_Initiative__c>  globalStrategicInitiatives { get; set; }
    
    public List<Account> globalStrategicContext { get; set; }
    
    public List<String> globalBuyingCriteria {get;set;}
    
    public Account account {get;set;}
    
    public Strategic_Initiative__c newInitiative {get;set;}
    
    public Account_Competitor__c newCompetitor {get;set;}
    
    public List<Account_Competitor__c> newCompetitors {get;set;}
    
    public List<Account_Competitor__c> competidores {get; set;}
    public Integer year {get;set;}
    
    public String delid {
        get;
        set {
            delid = value;
        }
    }
    public Boolean canEdit {get;set;}
    
    public Descripcion_del_cliente_New__c descripcionDelClienteActual {get; set;}
    
    public accountStrategicContextWindow(){
        
        if (Util.globalAccount==null) {
            
            this.account = [SELECT name, id, parentId, Industry,Region__c, Buying_Criteria_Last_Update__c , Strategic_Context__c, Buying_Criteria__c, Strategic_Context_Last_Update__c,
                            Brand_Strengths__c, Brand_Weakness__c, Brand_Opportunities__c, Brand_Threats__c,
                            Products_Services_Strengths__c, Products_Services_Weakness__c, Products_Services_Opportunities__c, Products_Services_Threats__c,
                            People_Strengths__c, People_Weakness__c, People_Opportunities__c, People_Threats__c,
                            Other_Strengths__c, Other_Weakness__c, Other_Opportunities__c, Other_Threats__c,
                            CSAT_Unit__c, CSAT_Current_Year__c, CSAT_Last_Year__c, CSAT_Second_To_Last_Year__c
                            FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
        } else {
            this.account = Util.globalAccount; 
        }
        this.loadData();
        //Funcion que engloba si el el usuario acutal puede o no escribir en esta cuenta
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);
        
        List<Descripcion_del_cliente_New__c> descripciones = new List<Descripcion_del_cliente_New__c>();
        
        
        descripciones = [select id, El_n_mero_de_sucursales_crece_decrece__c, Cantidad_de_edificios__c, cantidad_de_empleados__c,
                         cantidad_de_sucursales__c, dispone_de_parque_automotor__c, Parque_Automotor_Propio_o_Gestionado__c, Presupuesto_anual_que_maneja_tu_cliente__c,
                         siguientes_pa_ses_tienen_negocio__c, Strategic_Context__c, Strategic_Context_Last_Update__c, veh_culos_dispone_el_parque__c, CSAT_Current_Year__c, CSAT_Last_Year__c, CSAT_Second_To_Last_Year__c, CSAT_Unit__c
                         from Descripcion_del_cliente_New__c
                         where cuenta__c =: account.id
                         limit 1];
        
        
        if(descripciones.size() > 0){
            descripcionDelClienteActual = descripciones[0];
        }
        
        newCompetitors = new List<Account_Competitor__c>();
        
        newCompetitors = [SELECT Id, Name, Fact__c, LastModifiedDate FROM Account_Competitor__c where Account__c = :account.Id order by createdDate];
        system.debug(newCompetitors.size());
        //InsertCompetitor();
		
        /*
        Account_Competitor__c c = new Account_Competitor__c();
        c.name = 'asjfhjasdg';
        newCompetitors.add(c);
        */
        newCompetitor = new Account_Competitor__c(Account__c = account.id);
        
        Date today = Date.today();
        
        year = today.year();
        
        
    }
    
    public void insertarData(){
        
        List<Descripcion_del_cliente_New__c> tengoDescripciones = [select id, El_n_mero_de_sucursales_crece_decrece__c, Cantidad_de_edificios__c, cantidad_de_empleados__c,
                                                               cantidad_de_sucursales__c, dispone_de_parque_automotor__c, Parque_Automotor_Propio_o_Gestionado__c, Presupuesto_anual_que_maneja_tu_cliente__c,
                                                               siguientes_pa_ses_tienen_negocio__c, Strategic_Context__c, Strategic_Context_Last_Update__c, veh_culos_dispone_el_parque__c, CSAT_Current_Year__c, CSAT_Last_Year__c, CSAT_Second_To_Last_Year__c, CSAT_Unit__c
                                                               from Descripcion_del_cliente_New__c
                                                               where cuenta__c =: account.id
                                                               limit 1];
        
        if(tengoDescripciones.size()==0){
            
            descripcionDelClienteActual = new Descripcion_del_cliente_New__c();
            descripcionDelClienteActual.cuenta__c = account.id;
            insert descripcionDelClienteActual;
        }
    }
    
    public void loadData(){
        
        newInitiative = new Strategic_Initiative__c();
        globalStrategicContext = new List<Account>();
        globalBuyingCriteria = new List<String>();
        globalStrategicInitiatives = new List<Strategic_Initiative__c>();
        
        
        localStrategicInitiatives = [SELECT Name, Strategic_Initiative__c, Strategic_Initiative_URL__c, LastModifiedDate, account__r.name, Title__c, (SELECT name, Opportunity__c, Opportunity__r.Name FROM Opportunities__r WHERE Opportunity__r.Account.id = :this.account.id) FROM Strategic_Initiative__c WHERE Account__C = :this.account.id order by name];
        
        
        Account accents = new Account();
        
        
        List<Account> cuentas = [SELECT Name, id, parentId, Industry,Region__c, Buying_Criteria_Last_Update__c,Strategic_Context__c, Buying_Criteria__c, Strategic_Context_Last_Update__c FROM Account WHERE Id = :this.account.parentId];
        
        if(cuentas.size()>0){
            accents = cuentas[0];
        }
        
        
        
        
        
        if(account.parentId != null)
            getDataFromParents(accents);
    }
    
    public void getDataFromParents(Account a){
        Account accents2 = new Account();
        
        
        List<Account> cuentas = [SELECT name, id, parentId, Buying_Criteria_Last_Update__c,Industry,Region__c, Strategic_Context__c, Buying_Criteria__c, Strategic_Context_Last_Update__c FROM Account WHERE Id = :a.parentId];
        if(cuentas.size()>0)
            accents2 = cuentas[0];
        
        
        if(a.parentId != null){
            getDataFromParents(accents2);
        }
        if(a.Strategic_Context__c!=null && a.Strategic_Context__c!='') {
            globalStrategicContext.add(a);
        }
        
        if(a.Buying_Criteria__c!=null && a.Buying_Criteria__c!='') {
            globalBuyingCriteria.add(a.Buying_Criteria__c);
        }
        
        List<Strategic_Initiative__c> temp = new List<Strategic_Initiative__c>();
        
        
        temp = [SELECT name,Strategic_Initiative__c,Strategic_Initiative_URL__c, LastModifiedDate, account__r.name, (SELECT name, Opportunity__c, Opportunity__r.name FROM Opportunities__r  WHERE Opportunity__r.Account.Id = :this.account.id) FROM Strategic_Initiative__c WHERE Account__C = :a.id order by Name];
        
        
        System.Debug( temp);
        System.Debug( globalStrategicInitiatives);
        
        if(temp != null) {
            globalStrategicInitiatives.addAll(temp);
        }        
        
    }

    public PageReference SaveChanges() {        
        
        Account oldAccount = new Account();
        Descripcion_del_cliente_New__c oldDescription = new Descripcion_del_cliente_New__c();
        
        oldDescription =  [select id, Strategic_Context__c, Strategic_Context_Last_Update__c
                         from Descripcion_del_cliente_New__c
                         where cuenta__c =: account.id
                         limit 1];
        
        
        oldAccount = [select id, Strategic_Context__c, Buying_Criteria__c from Account where id = :account.id];
        
        
        if (descripcionDelClienteActual.Strategic_Context__c != oldDescription.Strategic_Context__c) {
            if (Schema.sObjectType.Descripcion_del_cliente_New__c.fields.Strategic_Context_Last_Update__c.isUpdateable() ){
                descripcionDelClienteActual.Strategic_Context_Last_Update__c=System.now();
            }
        }
        
        if (account.Buying_Criteria__c != oldAccount.Buying_Criteria__c) {
            if (Schema.sObjectType.account.fields.Buying_Criteria_Last_Update__c.isUpdateable() ){
                account.Buying_Criteria_Last_Update__c=System.now();
            }
        }
        
        if (Schema.sObjectType.account.isUpdateable() && Schema.sObjectType.Descripcion_del_cliente_New__c.isUpdateable() ){
            update account; 
            update descripcionDelClienteActual;
        }
        
        system.debug(newCompetitors);
        
        List<Account_Competitor__c> lista_ac=new List<Account_Competitor__c>();
        List<Account_Competitor__c> lista_ac2=new List<Account_Competitor__c>();
        
        if(newCompetitors == null){
            newCompetitors = new List<Account_competitor__C>();
        }
        for(Account_Competitor__c ac:newCompetitors){
            if((((ac.Name!='' && ac.Name!=null) || (ac.Fact__c!='' && ac.Fact__c!=null)) && ac.id==null) || ac.id!=null)
                lista_ac.add(ac);
        }
        
        Savepoint sp = Database.setSavepoint();
        try {
            
            system.debug('entre');
            upsert lista_ac;
            
            update account;		        
        } catch(DmlException ex){
            Database.rollback(sp);
            ApexPages.addMessages(ex);
        } 
        
        
        newCompetitors = [SELECT Id, Name, Fact__c, LastModifiedDate FROM Account_Competitor__c where Account__c = :account.Id order by createdDate];
        
        update descripcionDelClienteActual;
        
        
        
        upsert localStrategicInitiatives;
        
        
        return null;
    }
    
    public void InsertIniciative() {
        
        if (Schema.sObjectType.Strategic_Initiative__c.fields.account__c.isCreateable()){
            newInitiative.account__c = account.id;}
        
        if (Schema.sObjectType.Strategic_Initiative__c.isCreateable()){
            insert newInitiative;
        }
        
        loadData();
        
    }
    
    public void DeleteStrategicInitiatives() {
        
        Integer i = 0;
        
        for(Strategic_Initiative__c si : localStrategicInitiatives){
            
            if(si.id == this.delid){
                break;
            }
            else
                i++;
            
        }
        
        if(localStrategicInitiatives[i].id != null){
            List<OpportunityStrategicInitiative__c> osi = new List<OpportunityStrategicInitiative__c>();
            
            if(Schema.sObjectType.OpportunityStrategicInitiative__c.isAccessible()){
                osi=[select Id from OpportunityStrategicInitiative__c where Strategic_Initiative__c = :localStrategicInitiatives[i].id];}
            
            
            if(OpportunityStrategicInitiative__c.sObjectType.getDescribe().isDeletable()){
                delete osi;
            }
            
            if(Strategic_Initiative__c.sObjectType.getDescribe().isDeletable()){
                delete localStrategicInitiatives[i];
            }    
        }
        
        localStrategicInitiatives.remove(i);
        
    }
    
    public void borra(){
        if (Schema.sObjectType.Descripcion_del_cliente_New__c.fields.Strategic_Context_Last_Update__c.isUpdateable() && Schema.sObjectType.Descripcion_del_cliente_New__c.fields.Strategic_Context__c.isUpdateable() ){
            descripcionDelClienteActual.Strategic_Context_Last_Update__c=null;
            descripcionDelClienteActual.Strategic_Context__c=null;
            update descripcionDelClienteActual;
        }
        
        //init();
    }
    
    public void borra2(){
        account.Buying_Criteria__c=null;
        account.Buying_Criteria_Last_Update__c = null;
    }
    
    public PageReference ExportToExcel() {
        return Page.accountStrategicContextWindowExcel;
    }
    
    public String getExcelName() {
        String name = account.Name + '-' + Label.Client_Context + '.xls';
        return name.replaceAll(' ', '_').replaceAll(',','');
    }
    
    //Nuevas funcionalidades.
    public void DeleteCompetitor() {
        List<Account_Competitor__c> lista_ac=new List<Account_Competitor__c>();
        for(Account_Competitor__c ac:newCompetitors){
            if(ac.Id!=null && ac.Id==delid){
                if(Account_Competitor__c.sObjectType.getDescribe().isDeletable()){
                    delete ac;
                }
            }else{
                lista_ac.add(ac);
            }
        }
        newCompetitors=lista_ac;
    }
    
    public PageReference add() {
        
        insert newCompetitor;
        
        init();
        return null; 
    }
    
    public void InsertCompetitor() {
        newCompetitors.add(new Account_Competitor__c(Account__c = account.id));
    }
    
    private void init() {
        
        this.account = [SELECT name, id, parentId, Industry,Region__c, Buying_Criteria_Last_Update__c , Strategic_Context__c, Buying_Criteria__c, Strategic_Context_Last_Update__c,
                        Brand_Strengths__c, Brand_Weakness__c, Brand_Opportunities__c, Brand_Threats__c,
                        Products_Services_Strengths__c, Products_Services_Weakness__c, Products_Services_Opportunities__c, Products_Services_Threats__c,
                        People_Strengths__c, People_Weakness__c, People_Opportunities__c, People_Threats__c,
                        Other_Strengths__c, Other_Weakness__c, Other_Opportunities__c, Other_Threats__c,
                        CSAT_Unit__c, CSAT_Current_Year__c, CSAT_Last_Year__c, CSAT_Second_To_Last_Year__c
                        FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
        
        newCompetitors = new List<Account_Competitor__c>();
        
        newCompetitors = [SELECT Id, Name, Fact__c, LastModifiedDate FROM Account_Competitor__c where Account__c = :account.Id order by createdDate];
        
        //InsertCompetitor();
        newCompetitor = new Account_Competitor__c(Account__c = account.id);
        
        Date today = Date.today();
        
        //this.year = today.year() -1;
        year = today.year();
        
        //Funcion que engloba si el el usuario acutal puede o no escribir en esta cuenta
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);
    }
}