src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Contexto Estratégico</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Industria y Comercio</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Administración pública</fullName>
                </value>
                <value>
                    <fullName>Salud, Educación y Seguridad</fullName>
                </value>
                <value>
                    <fullName>Servicios y Tecnología</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PastProvenValueNew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Past Proven Value</label>
        <referenceTo>PastProvenValueNew__c</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Opportunity - PastProvenValueNew</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityPastProvenValueNew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Opportunity - PastProvenValueNew</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Project/Capability Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/test_accountIndustryTrends.cls
@isTest
private class test_accountIndustryTrends {
	
    static testMethod void myUnitTest2() {
        
        Integer driversCount = 0;
                      
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
		
        Account cuentaAbuelo=new Account();
        cuentaAbuelo.Name='test';
        cuentaAbuelo.Region__c=regionLocal.id;
        cuentaAbuelo.Strategic_Context__c = 'Test Cuenta Abuelo';
        insert cuentaAbuelo;
                
        Account cuentapapa=new Account();
        cuentapapa.Name='test';
        cuentapapa.Region__c=regionLocal.id;
        cuentapapa.ParentId = cuentaAbuelo.id;
        cuentapapa.Strategic_Context__c = 'Test Cuenta Padre';
        insert cuentapapa;        
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.ParentId = cuentapapa.id;
        cuenta.Strategic_Context__c = 'Test Cuenta';
        cuenta.Sector__c = 'sector';
        cuenta.Industry = 'industry';
        cuenta.Micro_Industry__c = 'Micro_Industry';
        insert cuenta;		        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test oppp';
        opp.StageName = 'Open';
        opp.CloseDate = system.today();
        opp.AccountId = cuenta.id;
        insert opp;
        
        Industry_Trend__c it = new Industry_Trend__c();
        it.Trend__c = 'test';
        it.Region__c = regionGlobal.id;
        it.Sector__c = cuenta.Sector__c;
        it.Sub_Sector__c = cuenta.Industry;
        it.Industry__c = cuenta.Micro_Industry__c;
        insert it;
        driversCount++;
        
        Strategic_Initiative__c si = new Strategic_Initiative__c();
        si.Account__c = cuenta.id;
        insert si;        
		driversCount++;
		
		Strategic_Initiative__c si2 = new Strategic_Initiative__c();
        si2.Account__c = cuentapapa.id;
        insert si2;
        driversCount++;
        
        PastProvenValueNew__c ppv = new PastProvenValueNew__c(account__c = cuenta.id);
        insert ppv;
        driversCount++;       
        
        System.currentPagereference().getParameters().put('id',cuenta.id);        
        accountIndustryTrends p_Test = new accountIndustryTrends();
        
        Integer trends = 0;
		for (ExtendedRegion region :p_Test.Regions) {
			trends += region.Trends.size();
		}
        
        Integer totalDrivers = p_Test.localStrategicInitiatives.size() + p_Test.globalStrategicInitiatives.size() + p_Test.provenValueWrapperList.size() + trends; 
		
		system.assert(p_Test.opportunities.size()==1);
		
		p_Test.oppid = opp.id;
		
		p_Test.trendid = it.id;
		p_Test.linkTrend();		
		List<OportunityIndustryTrend__c> oppItResult = [select id from OportunityIndustryTrend__c where opportunity__c = :opp.id];
		system.assert(oppItResult.size()==1);               
        p_Test.trendid = oppItResult.get(0).id;
        p_Test.unLinkTrend();
        List<OportunityIndustryTrend__c> oppItResult2 = [select id from OportunityIndustryTrend__c where opportunity__c = :opp.id];
		system.assert(oppItResult2.size()==0);   
		
		p_Test.getIndustry();
        p_Test.ExportToExcel();
        p_Test.getExcelName();
        p_Test.reverseList(p_Test.Regions);
        p_Test.ExportToExcelTrendWindows();     
        p_Test.getExcelNameTrendWindows();
    }

    static testMethod void myUnitTest3() {
        
        Integer driversCount = 0;
                      
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
		
        Account cuentaAbuelo=new Account();
        cuentaAbuelo.Name='test';
        cuentaAbuelo.Region__c=regionLocal.id;
        cuentaAbuelo.Strategic_Context__c = 'Test Cuenta Abuelo';
        insert cuentaAbuelo;
                
        Account cuentapapa=new Account();
        cuentapapa.Name='test';
        cuentapapa.Region__c=regionLocal.id;
        cuentapapa.ParentId = cuentaAbuelo.id;
        cuentapapa.Strategic_Context__c = 'Test Cuenta Padre';
        insert cuentapapa;        
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.ParentId = cuentapapa.id;
        cuenta.Strategic_Context__c = 'Test Cuenta';
        cuenta.Sector__c = 'sector';
        cuenta.Industry = 'industry';
        cuenta.Micro_Industry__c = 'Micro_Industry';
        insert cuenta;		        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test oppp';
        opp.StageName = 'Open';
        opp.CloseDate = system.today();
        opp.AccountId = cuenta.id;
        insert opp;
        
        Industry_Trend__c it = new Industry_Trend__c();
        it.Trend__c = 'test';
        it.Region__c = regionGlobal.id;
        it.Sector__c = cuenta.Sector__c;
        it.Sub_Sector__c = cuenta.Industry;
        it.Industry__c = cuenta.Micro_Industry__c;
        insert it;
        driversCount++;
        
        Strategic_Initiative__c si = new Strategic_Initiative__c();
        si.Account__c = cuenta.id;
        insert si;        
		driversCount++;
		
		Strategic_Initiative__c si2 = new Strategic_Initiative__c();
        si2.Account__c = cuentapapa.id;
        insert si2;
        driversCount++;
        
        PastProvenValueNew__c ppv = new PastProvenValueNew__c(account__c = cuenta.id);
        insert ppv;
        driversCount++;       
        
        System.currentPagereference().getParameters().put('id',cuenta.id);        
        accountIndustryTrends p_Test = new accountIndustryTrends();
        
        Integer trends = 0;
		for (ExtendedRegion region :p_Test.Regions) {
			trends += region.Trends.size();
		}
        
        Integer totalDrivers = p_Test.localStrategicInitiatives.size() + p_Test.globalStrategicInitiatives.size() + p_Test.provenValueWrapperList.size() + trends; 
		
		p_Test.oppid = opp.id;
		
        p_Test.iniciativeid = si.id;
		p_Test.linkIniciative();	
		List<OpportunityStrategicInitiative__c> oppIsResult = [select id from OpportunityStrategicInitiative__c where opportunity__c = :opp.id];
		system.assert(oppIsResult.size()==1);
		p_Test.iniciativeid = oppIsResult.get(0).id;
		p_Test.unLinkIniciative();		
		List<OpportunityStrategicInitiative__c> oppIsResult2 = [select id from OpportunityStrategicInitiative__c where opportunity__c = :opp.id];
		system.assert(oppIsResult2.size()==0);
    }

    static testMethod void myUnitTest4() {
                      
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
		
        Account cuentaAbuelo=new Account();
        cuentaAbuelo.Name='test';
        cuentaAbuelo.Region__c=regionLocal.id;
        cuentaAbuelo.Strategic_Context__c = 'Test Cuenta Abuelo';
        insert cuentaAbuelo;
        
        Account cuentapapa=new Account();
        cuentapapa.Name='test';
        cuentapapa.Region__c=regionLocal.id;
        cuentapapa.ParentId = cuentaAbuelo.id;
        cuentapapa.Strategic_Context__c = 'Test Cuenta Padre';
        insert cuentapapa;
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.ParentId = cuentapapa.id;
        cuenta.Strategic_Context__c = 'Test Cuenta';
        cuenta.Sector__c = 'sector';
        cuenta.Industry = 'industry';
        insert cuenta;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test oppp';
        opp.StageName = 'Open';
        opp.CloseDate = system.today();
        opp.AccountId = cuenta.id;
        insert opp;
        
        PastProvenValueNew__c ppv = new PastProvenValueNew__c(account__c = cuenta.id);
        insert ppv;
        
        System.currentPagereference().getParameters().put('id',cuenta.id);        
        accountIndustryTrends p_Test = new accountIndustryTrends();
		
		p_Test.oppid = opp.id;
   
    	p_Test.pastProventValueid = ppv.id;
		p_Test.linkPastProventValue();		
		List<OpportunityPastProvenValueNew__c> oppPpvResult = [select id from OpportunityPastProvenValueNew__c where opportunity__c = :opp.id];
		system.assert(oppPpvResult.size()==1);
		p_Test.pastProventValueid = oppPpvResult.get(0).id;
		p_Test.unLinkPastProventValue();		
		List<OpportunityPastProvenValueNew__c> oppPpvResult2 = [select id from OpportunityPastProvenValueNew__c where opportunity__c = :opp.id];
		system.assert(oppPpvResult2.size()==0);
    }
	
}