src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunityPastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PastProvenValueNew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Past Proven Value</label>
        <referenceTo>PastProvenValueNew__c</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Opportunity - PastProvenValueNew</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityPastProvenValueNew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Opportunity - PastProvenValueNew</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Project/Capability Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Titulo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Casos de exito en la cuenta</fullName>
                </value>
                <value>
                    <fullName>Diferenciadores competitivos en la cuenta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SCP Potential New Business</relationshipLabel>
        <relationshipName>GAP_Potential_New_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Past_Provent__c.object
<CustomObject>
    <fields>
        <fullName>Past_Proven_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Past Proven Value</label>
        <referenceTo>PastProvenValueNew__c</referenceTo>
        <relationshipName>Potential_New_Business_Past_Provent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Past_Provent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Past_Provent</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Past_Provent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Past_Provent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountPastProvenValueNewController.cls
public with sharing class AccountPastProvenValueNewController {
	
	public Account account {get;set;}
	public Boolean canEdit {get;set;}
	public List<PastProvenValueNew__c> pastProvenValueNewList {get;set;}	
	public String toDel {get;set;}
	public List<ProvenValueWrapper> provenValueWrapperList {get;set;}
	public PastProvenValueNew__c newProvenValue {get;set;}	
	
	public AccountPastProvenValueNewController() {        
        if (Util.globalAccount==null) {
        	if(Schema.sObjectType.Account.isAccessible() && Schema.sObjectType.Account.fields.Name.isAccessible()
        	&& Schema.sObjectType.Account.fields.parentId.isAccessible()
        	&& Schema.sObjectType.Account.fields.Industry.isAccessible()
        	&& Schema.sObjectType.Account.fields.Region__c.isAccessible()
        	&& Schema.sObjectType.Account.fields.micro_industry__c.isAccessible()){
        	account = [SELECT id, Name, parentId, Industry, micro_industry__c, Region__c FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];}    
        } else {
    		this.account = Util.globalAccount; 
    	}
    	
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account.id);                
        init();        
    }

	private void init() {
	
		newProvenValue = new PastProvenValueNew__c(account__c = account.id);
		
		pastProvenValueNewList = new List<PastProvenValueNew__c>();
		
		provenValueWrapperList = new List<ProvenValueWrapper>();	
		if (account.parentId != null) {
			List<Id> accountIdList = new List<Id>();
			List<account> accents = new List<account>();
		    
		    if(Schema.sObjectType.Account.isAccessible() ){	
		   	accents = [select id from account where (id = :account.parentId or parentId = :account.parentId) and id != :account.id];
		}
			for (Account acc : accents) {
				accountIdList.add(acc.id);				
			}
			
			List<PastProvenValueNew__c> valuesnewx = new List<PastProvenValueNew__c>();
			
			if(Schema.sObjectType.PastProvenValueNew__c.isAccessible() && Schema.sObjectType.PastProvenValueNew__c.fields.Name.isAccessible()
			&& Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isAccessible()
			&& Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isAccessible()
			&& Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isAccessible()
			&& Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isAccessible()
			&& Schema.sObjectType.PastProvenValueNew__c.fields.LastModifiedDate.isAccessible()){
			valuesnewx = [select id, name, account__c, Unique_Value__c, type__c, region__c, account__r.Name, LastModifiedDate, (SELECT name, Opportunity__c, Opportunity__r.Name FROM OpportunityPastProvenValueNew__r WHERE Opportunity__r.Account.id = :this.account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Past_Provent__r) from PastProvenValueNew__c where account__c in :accountIdList];}
			
			for (PastProvenValueNew__c p :valuesnewx) {
				provenValueWrapperList.add(new ProvenValueWrapper(p,p.account__r.Name,false));
			}	
		}
		
		Region__c region = Util.getRegionFromAccount(account.Id, account.region__c);		
		        
        loadProvenValueRegion(region, account.industry, account.micro_industry__c);
		
		List<PastProvenValueNew__c> valuesnewx2 = new List<PastProvenValueNew__c>();
		
		if(Schema.sObjectType.PastProvenValueNew__c.isAccessible() && Schema.sObjectType.PastProvenValueNew__c.fields.Name.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.title__c.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isAccessible()
		&& Schema.sObjectType.PastProvenValueNew__c.fields.LastModifiedDate.isAccessible()){
		valuesnewx2 = [select id, title__c, name, account__c, Unique_Value__c, type__c, region__c, LastModifiedDate, (SELECT name, Opportunity__c, Opportunity__r.Name FROM OpportunityPastProvenValueNew__r WHERE Opportunity__r.Account.id = :this.account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Past_Provent__r) from PastProvenValueNew__c where account__c = :account.id];}
		
		for (PastProvenValueNew__c p :valuesnewx2) {
			provenValueWrapperList.add(new ProvenValueWrapper(p,account.Name,true));
			pastProvenValueNewList.add(p);
		}
				
	}
	
	private void loadProvenValueRegion(Region__c region, String industry, String micro_industry) {
		
		Map<Id, Region__c> regionsMap = new Map<Id, Region__c>();
        List<Region__c> regionesx = new List<Region__c>();
        
        if(Schema.sObjectType.Region__c.isAccessible() && Schema.sObjectType.Region__c.fields.Name.isAccessible()
        && Schema.sObjectType.Region__c.fields.parent__c.isAccessible()){
        regionesx = [select id, Name, parent__c from Region__c limit 1000];}
        
        for (Region__c reg : regionesx) {
        	regionsMap.put(reg.id,reg);        	
        } 
        
        List<Region__c> regionsToSerch = new List<Region__c>();
        Id regionId = region.id;
        
        while (regionId != null) {
        	Region__c r = regionsMap.get(regionId);
        	regionsToSerch.add(r);
        	regionId = r.parent__c;
        }
        
        List<PastProvenValueNew__c> provenvalueneewX = new List<PastProvenValueNew__c>();
        
        if(Schema.sObjectType.PastProvenValueNew__c.isAccessible() && Schema.sObjectType.PastProvenValueNew__c.fields.Name.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.industry__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.micro_industry__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isAccessible()
        && Schema.sObjectType.PastProvenValueNew__c.fields.LastModifiedDate.isAccessible()){
        provenvalueneewX = [select id, name, account__c, Unique_Value__c, type__c, industry__c, micro_industry__c, region__c, region__r.Name, LastModifiedDate, (SELECT name, Opportunity__c, Opportunity__r.Name FROM OpportunityPastProvenValueNew__r WHERE Opportunity__r.Account.id = :this.account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Past_Provent__r) from PastProvenValueNew__c where (industry__c = :industry or industry__c = 'All' or industry__c = 'Todos') and (micro_industry__c = :micro_industry or micro_industry__c = 'All' or micro_industry__c = 'Todos') and region__c in :regionsToSerch];}
        
        for (PastProvenValueNew__c p :provenvalueneewX) {
			provenValueWrapperList.add(new ProvenValueWrapper(p,p.region__r.Name+' ('+p.industry__c+' - '+ p.micro_industry__c +')',false));
		}
	}
	
	public PageReference add() {
		try {
		    if(Schema.sObjectType.PastProvenValueNew__c.fields.Account__c.isCreateable() &&
	        Schema.sObjectType.PastProvenValueNew__c.isCreateable()){
			    insert newProvenValue;
	        }
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }
		init();
		return null;
	}
	
	public PageReference save() {
		boolean errors = false;
		
		for (PastProvenValueNew__c past :pastProvenValueNewList) {
			if (past.type__c == null) {
				errors = true;
				past.type__c.addError('Debe escribir un valor');
			}
		}
		
		if (!errors) { 
			try {
			    
                system.debug(Schema.sObjectType.PastProvenValueNew__c.isCreateable());
                system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.title__c.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.name.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isCreateable());
				//system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.LastModifiedDate.isCreateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.isUpdateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.title__c.isUpdateable());
				//system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.name.isUpdateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isUpdateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isUpdateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isUpdateable());
				system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isUpdateable());
                //system.debug( Schema.sObjectType.PastProvenValueNew__c.fields.LastModifiedDate.isUpdateable());
				
                
                if(Schema.sObjectType.PastProvenValueNew__c.isCreateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.title__c.isCreateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isCreateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isCreateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isCreateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isCreateable()

                   && Schema.sObjectType.PastProvenValueNew__c.isUpdateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.title__c.isUpdateable()

                   && Schema.sObjectType.PastProvenValueNew__c.fields.account__c.isUpdateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.Unique_Value__c.isUpdateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.type__c.isUpdateable()
                   && Schema.sObjectType.PastProvenValueNew__c.fields.region__c.isUpdateable()){
                       upsert pastProvenValueNewList;
                   }
                
		    } catch(DmlException ex){
		        ApexPages.addMessages(ex);
		    }
			init();
		}
		
		return null;		
	}
	
	public PageReference del() { 
		try {
			PastProvenValueNew__c aBorrar = new PastProvenValueNew__c();
			
			if(Schema.sObjectType.PastProvenValueNew__c.isAccessible()){
           aBorrar = [select id from PastProvenValueNew__c where id = :toDel];}
          
            if (!PastProvenValueNew__c.sObjectType.getDescribe().isDeletable()){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,
                                                           'Acceso insuficiente.')); 
                return null;
            }
            
           if(PastProvenValueNew__c.sObjectType.getDescribe().isDeletable()){
               delete aBorrar;
           }
            
	    } catch(DmlException ex){
	        ApexPages.addMessages(ex);
	    }			   	
    	init();
    	return null;
    }
    
    public PageReference ExportToExcel() { 
		save();   	
    	return Page.accountPastProvenValueNewExcel;
    }
    
    public String getExcelName() {
    	String name = account.Name + '-' + Organization.Name + ' ' + Label.account_past_proven_value + '.xls';
    	return name.replaceAll(' ', '_').replaceAll(',','');
    }
        
    public class ProvenValueWrapper {
    	public PastProvenValueNew__c provenValue {get;set;}
    	public String source {get;set;}
    	public Boolean canEdit {get;set;}
    
    	public ProvenValueWrapper(PastProvenValueNew__c p, String s, Boolean c) {
    		provenValue = p;
    		source = s.replace('Todos - Todos', 'Todos').replace('All - All', 'All');	
    		canEdit = c;
    	}
    		
    }
	
}