src/objects/Area_de_trabajo__c.object
<CustomObject>
    <fields>
        <fullName>Conocimiento_del_Area__c</fullName>
        <label>Conocimiento del Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
                <value>
                    <fullName>Aún no tengo contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Areas de trabajo</relationshipLabel>
        <relationshipName>Areas_de_trabajo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Area__c</fullName>
        <label>Tipo de Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Sistemas</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
                <value>
                    <fullName>Digitalización</fullName>
                </value>
                <value>
                    <fullName>Transformación</fullName>
                </value>
                <value>
                    <fullName>Financiera</fullName>
                </value>
                <value>
                    <fullName>Área de Negocio</fullName>
                </value>
                <value>
                    <fullName>RRHH</fullName>
                </value>
                <value>
                    <fullName>Bienes e Inmuebles</fullName>
                </value>
                <value>
                    <fullName>Áreas Corporativas</fullName>
                </value>
                <value>
                    <fullName>Producción</fullName>
                </value>
                <value>
                    <fullName>Ninguna de las anteriores</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area de trabajo</label>
    <nameField>
        <label>Nombre de Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas de trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto__c.object
<CustomObject>
    <fields>
        <fullName>Area_de_trabajo__c</fullName>
        <label>Area de trabajo</label>
        <referenceTo>Area_de_trabajo__c</referenceTo>
        <relationshipLabel>Retos</relationshipLabel>
        <relationshipName>Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competidor__c</fullName>
        <label>Competidor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Etapa_del_Reto__c</fullName>
        <label>Etapa del Reto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cerrar</fullName>
                </value>
                <value>
                    <fullName>Prospección</fullName>
                </value>
                <value>
                    <fullName>Diseño</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Compras</fullName>
                </value>
                <value>
                    <fullName>Implementación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reto</label>
    <nameField>
        <label>Nombre de Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EjesDeTrabajoTest.cls
@isTest
public class EjesDeTrabajoTest {

    static testMethod void test1(){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Area_de_trabajo__c area1 = new Area_de_trabajo__c();
        area1.Name = 'Area1';
        area1.Cuenta__c = cuenta.id;
        area1.Tipo_de_Area__c = 'Comunicaciones';
        area1.Conocimiento_del_Area__c = 'Alto';
        insert area1;
        
        Reto__c reto1 = new Reto__c();
        reto1.Nombre_del_Reto__c = 'Reto1';
        reto1.Area_de_trabajo__c = area1.id;
        reto1.Competidor__c = 'dasdasdas';
        reto1.Etapa_del_Reto__c = 'Compras';
        insert reto1;        
        
        Reto__c reto2 = new Reto__c();
        reto2.Nombre_del_Reto__c = 'Reto2';
        reto2.Area_de_trabajo__c = area1.id;
        reto2.Competidor__c = 'lolololo';
        reto1.Etapa_del_Reto__c = 'Diseño';
        insert reto2; 
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        EjesDeTrabajoController controller = new EjesDeTrabajoController();
        
        system.assertEquals(1, controller.areasDeTrabajo.size());
        system.assertEquals(1, controller.areas.size());
        system.assertEquals(2, controller.retosAreas.size());
    }
    	
}