src/objects/Area_de_trabajo__c.object
<CustomObject>
    <fields>
        <fullName>Conocimiento_del_Area__c</fullName>
        <label>Conocimiento del Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
                <value>
                    <fullName>Aún no tengo contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Areas de trabajo</relationshipLabel>
        <relationshipName>Areas_de_trabajo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Area__c</fullName>
        <label>Tipo de Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Sistemas</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
                <value>
                    <fullName>Digitalización</fullName>
                </value>
                <value>
                    <fullName>Transformación</fullName>
                </value>
                <value>
                    <fullName>Financiera</fullName>
                </value>
                <value>
                    <fullName>Área de Negocio</fullName>
                </value>
                <value>
                    <fullName>RRHH</fullName>
                </value>
                <value>
                    <fullName>Bienes e Inmuebles</fullName>
                </value>
                <value>
                    <fullName>Áreas Corporativas</fullName>
                </value>
                <value>
                    <fullName>Producción</fullName>
                </value>
                <value>
                    <fullName>Ninguna de las anteriores</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo_Area__c</fullName>
        <label>Titulo Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Area de trabajo</label>
    <nameField>
        <label>Nombre de Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas de trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto__c.object
<CustomObject>
    <fields>
        <fullName>Area_de_trabajo__c</fullName>
        <label>Area de trabajo</label>
        <referenceTo>Area_de_trabajo__c</referenceTo>
        <relationshipLabel>Retos</relationshipLabel>
        <relationshipName>Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competidor__c</fullName>
        <label>Competidor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Etapa_del_Reto__c</fullName>
        <label>Etapa del Reto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cerrar</fullName>
                </value>
                <value>
                    <fullName>Prospección</fullName>
                </value>
                <value>
                    <fullName>Diseño</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Compras</fullName>
                </value>
                <value>
                    <fullName>Implementación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fecha_Compromiso__c</fullName>
        <label>Fecha Compromiso</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nota__c</fullName>
        <label>Nota</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Reto</label>
    <nameField>
        <label>Nombre de Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto_tecnologia__c.object
<CustomObject>
    <fields>
        <fullName>Lista_de_Soluciones__c</fullName>
        <label>Lista de Soluciones</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Conectividad</fullName>
                </value>
                <value>
                    <fullName>Movilidad</fullName>
                </value>
                <value>
                    <fullName>Virtualización y Computación en modo Opex</fullName>
                </value>
                <value>
                    <fullName>Internet de las Cosas/Control de Objetos</fullName>
                </value>
                <value>
                    <fullName>Omnicanalidad</fullName>
                </value>
                <value>
                    <fullName>Digital WorkPlace (Puesto de Trabajo Digital)</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nivel_de_Desarrollo__c</fullName>
        <label>Nivel de Desarrollo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Disponible</fullName>
                </value>
                <value>
                    <fullName>En Desarrollo</fullName>
                </value>
                <value>
                    <fullName>No Disponible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Observaci_n_sobre_el_producto__c</fullName>
        <label>Observación sobre el producto</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Otra_Solucion__c</fullName>
        <label>Otra Solucion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>Reto</label>
        <referenceTo>Reto__c</referenceTo>
        <relationshipLabel>Reto tecnologias</relationshipLabel>
        <relationshipName>Reto_tecnologias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reto tecnologia</label>
    <nameField>
        <label>Nombre de Reto tecnologias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reto tecnologias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retos_Contacto__c.object
<CustomObject>
    <fields>
        <fullName>Contacto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacto</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reto Contactos</relationshipLabel>
        <relationshipName>Reto_Contactos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel_de_Relaci_n__c</fullName>
        <label>Nivel de Relación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fluida y Constante</fullName>
                </value>
                <value>
                    <fullName>Ocasional pero Cordial</fullName>
                </value>
                <value>
                    <fullName>Intensa y Difícil</fullName>
                </value>
                <value>
                    <fullName>No lo conozco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Otro_contacto_del_cliente__c</fullName>
        <label>Otro contacto del cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>Reto</label>
        <referenceTo>Reto__c</referenceTo>
        <relationshipLabel>Reto Contactos</relationshipLabel>
        <relationshipName>Reto_Contactos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Contacto__c</fullName>
        <label>Tipo de Contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reto Contacto</label>
    <nameField>
        <label>Nombre de Retos Contacto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reto Contactos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AreasDeTrabajoController.cls
public with sharing class AreasDeTrabajoController {
	
    public String idCuenta {get; set;}
    public List<WrapperArea> wrappersDeArea {get; set;}
    
    public String areaABorrarId {get; set;}
    
    public String solucionIdABorrar {get; set;}
    public String contactoIdABorrar {get; set;}
    public Id retoDeContactoABorrar {get; set;}
    
    
    public String idDelRetoDelContacto {get; set;}
    
    public Area_de_trabajo__c areaAInsertar {get; set;}
    public Retos_Contacto__c contactoAInsertar {get; set;}
    public Reto_tecnologia__c solucionAInsertar {get; set;}
    
    public List<Area_de_trabajo__c> areas {get; set;}
    public List<Reto__c> retos {get; set;}
    
    public AreasDeTrabajoController(){
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
        
        areaAInsertar = new Area_de_trabajo__c();
        contactoAInsertar = new Retos_Contacto__c();
        solucionAInsertar = new Reto_tecnologia__c(); 
        
       	obtenerAreasYGenerarWpp();
        
    }

    public void obtenerAreasYGenerarWpp(){
        
        areas = new List<Area_de_trabajo__c>();
        retos = new List<Reto__c>();
        
        if(Schema.sObjectType.Area_de_trabajo__c.isAccessible() && Schema.sObjectType.Area_de_trabajo__c.fields.Conocimiento_del_Area__c.isAccessible()
        && Schema.sObjectType.Area_de_trabajo__c.fields.Tipo_de_Area__c.isAccessible()
        && Schema.sObjectType.Area_de_trabajo__c.fields.Titulo_Area__c.isAccessible()){
        areas = [select id, Conocimiento_del_Area__c, Tipo_de_Area__c, Titulo_Area__c
                 from Area_de_trabajo__c
                 where cuenta__c =: idCuenta];
        }
        
        Set<String> idAreas = new Set<String>();
        for(Area_de_trabajo__c area: areas){
            idAreas.add(area.id);
        }
        
        if(Schema.sObjectType.Reto__c.isAccessible() && Schema.sObjectType.Reto__c.fields.Competidor__c.isAccessible()
        && Schema.sObjectType.Reto__c.fields.Etapa_del_Reto__c.isAccessible()
        && Schema.sObjectType.Reto__c.fields.Fecha_Compromiso__c.isAccessible()
        && Schema.sObjectType.Reto__c.fields.Nombre_del_Reto__c.isAccessible()
        && Schema.sObjectType.Reto__c.fields.Nota__c.isAccessible()
        && Schema.sObjectType.Reto__c.fields.Area_de_trabajo__c.isAccessible()){
        retos = [select id, Competidor__c, Etapa_del_Reto__c, Fecha_Compromiso__c, Nombre_del_Reto__c, Nota__c, Area_de_trabajo__c,
                 (select id, Contacto__c, Nivel_de_Relaci_n__c, Otro_contacto_del_cliente__c, Tipo_de_Contacto__c, Reto__c from Reto_Contactos__r),
                 (select id, Lista_de_Soluciones__c, Nivel_de_Desarrollo__c, Observaci_n_sobre_el_producto__c, Otra_Solucion__c, Reto__c from Reto_tecnologias__r)
                 from Reto__c
                 where Area_de_trabajo__c IN: idAreas];}
        
        Map<Area_de_trabajo__c, List<Reto__c>> areasConSusRetos = new Map<Area_de_trabajo__c, List<Reto__c>>();
        
        for(Area_de_trabajo__c area: areas){
            
            List<Reto__c> retosDelArea = new List<Reto__c>();
            for(Reto__c reto: retos){
                if(reto.Area_de_trabajo__c == area.id){
                    retosDelArea.add(reto);
                }
            }
            
            areasConSusRetos.put(area, retosDelArea); 
        }
        
        wrappersDeArea = new List<WrapperArea>();
        
        for(Area_de_trabajo__c area: areas){
            WrapperArea wppArea = new WrapperArea(area);
            wppArea.retos = areasConSusRetos.get(area);
            
            wrappersDeArea.add(wppArea);
        }
    }	
    
    public void guardar(){
        
        if(Schema.sObjectType.Area_de_trabajo__c.isUpdateable()){
            update areas;
        }
        
        if(Schema.sObjectType.Reto__c.isUpdateable()){
            update retos;
        }
    }
    
    public PageReference borrarArea(){
        
        Integer i = 0;
        
        for(WrapperArea wppArea : wrappersDeArea){
            
            if(wppArea.area.id == areaABorrarId){
                break;
            }
            else{
                i++;
            }   
        }
        
        if(wrappersDeArea[i].area.id != null){
            if(Area_de_trabajo__c.sObjectType.getDescribe().isDeletable()){
                delete wrappersDeArea[i].area;
            }    
        }
        
        
        wrappersDeArea.remove(i);        
        
        return null;
    }
    
    //Solucionar Borrar.
    public PageReference borrarContacto(){
        
        
        Reto__c retoDuenioDelContacto;
        for(Reto__c reto:retos){
            
            if(reto.id == retoDeContactoABorrar){
                retoDuenioDelContacto = reto; 
            }
            
        }
        
        if(retoDuenioDelContacto != null){
            
            Integer i = 0;
            
            for(Retos_Contacto__c contacto : retoDuenioDelContacto.Reto_Contactos__r){
                
                if(contacto.id == contactoIdABorrar){
                    break;
                }
                else{
                    i++;
                }   
            }
            
            if(retoDuenioDelContacto.Reto_Contactos__r[i].id != null){
                
                if(Retos_Contacto__c.sObjectType.getDescribe().isDeletable()){
                    delete retoDuenioDelContacto.Reto_Contactos__r[i];    
                }
            }
			
			
            obtenerAreasYGenerarWpp();
        }
        
        return null;
    }
    
    public PageReference borrarSolucion(){
        
        
        Reto__c retoDuenioDelContacto;
        for(Reto__c reto:retos){
            
            if(reto.id == retoDeContactoABorrar){
                retoDuenioDelContacto = reto; 
            }
            
        }
        
        if(retoDuenioDelContacto != null){
            
            Integer i = 0;
            
            for(Reto_tecnologia__c solucion : retoDuenioDelContacto.Reto_tecnologias__r){
                
                if(solucion.id == solucionIdABorrar){
                    break;
                }
                else{
                    i++;
                }   
            }
            
            if(retoDuenioDelContacto.Reto_tecnologias__r[i].id != null){
                
                if(Reto_tecnologia__c.sObjectType.getDescribe().isDeletable()){
                    delete retoDuenioDelContacto.Reto_tecnologias__r[i];
                }
            }
            
            
            obtenerAreasYGenerarWpp();       
            
            
        }
        return null;
    }
    
    public void insertarArea(){
        
        if(areaAInsertar.Titulo_Area__c != null){
             if (Schema.sObjectType.Area_de_trabajo__c.fields.Cuenta__c.isCreateable()){
                 areaAInsertar.Cuenta__c = idCuenta;}
            
            if (Schema.sObjectType.Area_de_trabajo__c.isCreateable()){
                insert areaAInsertar;
            }
            
            Reto__c reto1 = new Reto__c();
            
            if (Schema.sObjectType.Reto__c.fields.Area_de_trabajo__c.isCreateable()){
                reto1.Area_de_trabajo__c = areaAInsertar.id;}
            
            Reto__c reto2 = new Reto__c();
             
            if (Schema.sObjectType.Reto__c.fields.Area_de_trabajo__c.isCreateable()){
                 reto2.Area_de_trabajo__c = areaAInsertar.id;}
           
            Reto__c reto3 = new Reto__c();
             
            if (Schema.sObjectType.Reto__c.fields.Area_de_trabajo__c.isCreateable()){
                 reto3.Area_de_trabajo__c = areaAInsertar.id;}
            
            if (Schema.sObjectType.Reto__c.isCreateable()){
                insert reto1;
                insert reto2;
                insert reto3;
            }
        }
        
        areaAInsertar = new Area_de_trabajo__c();
        
        obtenerAreasYGenerarWpp();
    }
    
    public void insertarContacto(){
        
        if(!String.isBlank(idDelRetoDelContacto)){
            if (Schema.sObjectType.Retos_Contacto__c.fields.Reto__c.isCreateable()){
                contactoAInsertar.Reto__c = idDelRetoDelContacto;}
        }

        
        if(contactoAInsertar.Nivel_de_Relaci_n__c != null && contactoAInsertar.Tipo_de_Contacto__c != null && contactoAInsertar.Reto__c != null){
            system.debug(contactoAInsertar);
            
            if (Schema.sObjectType.Retos_Contacto__c.isCreateable()){
                insert contactoAInsertar;
            }
            
            contactoAInsertar = new Retos_Contacto__c();
            obtenerAreasYGenerarWpp();
        }
        
    }
    
    public void insertarSolucion(){

        if(!String.isBlank(idDelRetoDelContacto)){
            if (Schema.sObjectType.Reto_tecnologia__c.fields.Reto__c.isCreateable()){
                solucionAInsertar.Reto__c = idDelRetoDelContacto;}
        }
        
        
        if(solucionAInsertar.Nivel_de_Desarrollo__c != null && solucionAInsertar.Lista_de_Soluciones__c != null){
            
            if (Schema.sObjectType.Reto_tecnologia__c.isCreateable()){
                insert solucionAInsertar;
            }
            
            solucionAInsertar = new Reto_tecnologia__c();
            obtenerAreasYGenerarWpp();
        }
        
    }
    //======================================================================
    public class WrapperArea{
        
        public Area_de_trabajo__c area {get; set;}
        public List<Reto__c> retos {get; set;}
       // public List<WrapperReto> wppRetos {get; set;}
        
        public WrapperArea(Area_de_trabajo__c unArea){
            area = unArea;
            retos = new List<Reto__c>();
            //wppRetos = new List<WrapperReto>();
        }
    }
}