src/objects/Area_de_trabajo__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Areas de trabajo</relationshipLabel>
        <relationshipName>Areas_de_trabajo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Titulo_Area__c</fullName>
        <label>Titulo Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Area de trabajo</label>
    <nameField>
        <label>Nombre de Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas de trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto__c.object
<CustomObject>
    <fields>
        <fullName>Area_de_trabajo__c</fullName>
        <label>Area de trabajo</label>
        <referenceTo>Area_de_trabajo__c</referenceTo>
        <relationshipLabel>Retos</relationshipLabel>
        <relationshipName>Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reto</label>
    <nameField>
        <label>Nombre de Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reto_tecnologia__c.object
<CustomObject>
    <fields>
        <fullName>Lista_de_Soluciones__c</fullName>
        <label>Lista de Soluciones</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Conectividad</fullName>
                </value>
                <value>
                    <fullName>Movilidad</fullName>
                </value>
                <value>
                    <fullName>Virtualización y Computación en modo Opex</fullName>
                </value>
                <value>
                    <fullName>Internet de las Cosas/Control de Objetos</fullName>
                </value>
                <value>
                    <fullName>Omnicanalidad</fullName>
                </value>
                <value>
                    <fullName>Digital WorkPlace (Puesto de Trabajo Digital)</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nivel_de_Desarrollo__c</fullName>
        <label>Nivel de Desarrollo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Disponible</fullName>
                </value>
                <value>
                    <fullName>En Desarrollo</fullName>
                </value>
                <value>
                    <fullName>No Disponible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Observaci_n_sobre_el_producto__c</fullName>
        <label>Observación sobre el producto</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Otra_Solucion__c</fullName>
        <label>Otra Solucion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>Reto</label>
        <referenceTo>Reto__c</referenceTo>
        <relationshipLabel>Reto tecnologias</relationshipLabel>
        <relationshipName>Reto_tecnologias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reto tecnologia</label>
    <nameField>
        <label>Nombre de Reto tecnologias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reto tecnologias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retos_Contacto__c.object
<CustomObject>
    <fields>
        <fullName>Nivel_de_Relaci_n__c</fullName>
        <label>Nivel de Relación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fluida y Constante</fullName>
                </value>
                <value>
                    <fullName>Ocasional pero Cordial</fullName>
                </value>
                <value>
                    <fullName>Intensa y Difícil</fullName>
                </value>
                <value>
                    <fullName>No lo conozco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Otro_contacto_del_cliente__c</fullName>
        <label>Otro contacto del cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>Reto</label>
        <referenceTo>Reto__c</referenceTo>
        <relationshipLabel>Reto Contactos</relationshipLabel>
        <relationshipName>Reto_Contactos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Contacto__c</fullName>
        <label>Tipo de Contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reto Contacto</label>
    <nameField>
        <label>Nombre de Retos Contacto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reto Contactos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AreasDeTrabajoTest.cls
@isTest
public class AreasDeTrabajoTest {
        
    static testMethod void insertarAreas(){
        
        Account obj = new Account();
        obj.name = 'Cuenta';
        insert obj;
        
        Area_de_trabajo__c area1 = new Area_de_trabajo__c();
        area1.name = 'Area 1';
        area1.cuenta__c = obj.id;
        insert area1;
        
        Reto__c reto1 = new Reto__c();
        reto1.name = 'Reto 1';
        reto1.Area_de_trabajo__c = area1.id;
        insert reto1;
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(obj);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(obj.id));
        AreasDeTrabajoController controller = new AreasDeTrabajoController();
        
        system.assertEquals(1, controller.areas.size());
        system.assertEquals(1, controller.wrappersDeArea.size());
        
    }
    
    static testMethod void borrarYAgregarAreas(){
        
        Account obj = new Account();
        obj.name = 'Cuenta';
        insert obj;
        
        Area_de_trabajo__c area1 = new Area_de_trabajo__c();
        area1.name = 'Area 1';
        area1.cuenta__c = obj.id;
        insert area1;
        
        Reto__c reto1 = new Reto__c();
        reto1.name = 'Reto 1';
        reto1.Area_de_trabajo__c = area1.id;
        insert reto1;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(obj);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(obj.id));
        AreasDeTrabajoController controller = new AreasDeTrabajoController();
        
        system.assertEquals(1, controller.areas.size());
        system.assertEquals(1, controller.wrappersDeArea.size());
        
        controller.areaABorrarId = area1.id;
        controller.borrarArea();
        controller.borrarSolucion();
        
        system.assertEquals(0, controller.wrappersDeArea.size());  
        
        Area_de_trabajo__c area2 = new Area_de_trabajo__c();
        area2.name = 'Area 2';
        area2.Titulo_Area__c = 'Area2';
                        
        controller.areaAInsertar = area2;
        controller.insertarArea();
        controller.obtenerAreasYGenerarWpp();
    	
        system.assertEquals(1, controller.wrappersDeArea.size());
        
     }
    
    static testMethod void borrarYAgregarTecnologias(){
        //List<String> listita = new List<String>();
        
        Account obj = new Account();
        obj.name = 'Cuenta';
        insert obj;
        
        Area_de_trabajo__c area1 = new Area_de_trabajo__c();
        area1.name = 'Area 1';
        area1.cuenta__c = obj.id;
        insert area1;
        
        Reto__c reto1 = new Reto__c();
        reto1.name = 'Reto 1';
        reto1.Area_de_trabajo__c = area1.id;
        insert reto1;
        
        Retos_Contacto__c retoContacto1 = new Retos_Contacto__c();
        retoContacto1.name = 'Reto Contacto 1';
        retocontacto1.Reto__c = reto1.id;
        insert retoContacto1;
        
        Reto_tecnologia__c retoTecnologia1 = new Reto_tecnologia__c();
        retoTecnologia1.name = 'Reto Tecno 1';
        retoTecnologia1.Reto__c = reto1.id;
        retoTecnologia1.Nivel_de_Desarrollo__c = 'Disponible';
        retoTecnologia1.Lista_de_Soluciones__c = 'Movilidad';
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(obj);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(obj.id));
        AreasDeTrabajoController controller = new AreasDeTrabajoController();
        
        List<Reto_tecnologia__c> retos = new List<Reto_tecnologia__c>();
        
        retos = [select id, Lista_de_Soluciones__c, Nivel_de_Desarrollo__c, Observaci_n_sobre_el_producto__c, Otra_Solucion__c, Reto__c from Reto_tecnologia__c];
        
        system.assertEquals(0, retos.size());
        
        controller.solucionAInsertar = retoTecnologia1;
        
        controller.insertarSolucion();
        
        retos = [select id, Lista_de_Soluciones__c, Nivel_de_Desarrollo__c, Observaci_n_sobre_el_producto__c, Otra_Solucion__c, Reto__c from Reto_tecnologia__c];
        
        system.assertEquals(1, retos.size());
        
        controller.solucionIdABorrar = retoTecnologia1.id;
        
        controller.retoDeContactoABorrar = reto1.id;
        
        controller.borrarSolucion();
        
         retos = [select id, Lista_de_Soluciones__c, Nivel_de_Desarrollo__c, Observaci_n_sobre_el_producto__c, Otra_Solucion__c, Reto__c from Reto_tecnologia__c];
        
        system.assertEquals(0, retos.size());
                
        
    }
    
    static testMethod void borrarYAgregarContactos(){
        Account obj = new Account();
        obj.name = 'Cuenta';
        insert obj;
        
        Area_de_trabajo__c area1 = new Area_de_trabajo__c();
        area1.name = 'Area 1';
        area1.cuenta__c = obj.id;
        insert area1;
        
        Reto__c reto1 = new Reto__c();
        reto1.name = 'Reto 1';
        reto1.Area_de_trabajo__c = area1.id;
        insert reto1;
        
        Retos_Contacto__c retoContacto1 = new Retos_Contacto__c();
        retoContacto1.name = 'Reto Contacto 1';
        retoContacto1.Reto__c = reto1.id;
        retoContacto1.Nivel_de_Relaci_n__c = 'Fluida y Constante';
        retoContacto1.Tipo_de_Contacto__c = 'CEO';
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(obj);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(obj.id));
        AreasDeTrabajoController controller = new AreasDeTrabajoController();
        
        controller.contactoAInsertar = retoContacto1;
        controller.retoDeContactoABorrar = reto1.id;
        
        List<Retos_Contacto__c> contactos = new List<Retos_Contacto__c>();
        
        contactos = [select id, Nivel_de_Relaci_n__c, Otro_contacto_del_cliente__c, Tipo_de_Contacto__c, Reto__c from Retos_Contacto__c];
        
        system.assertEquals(0, contactos.size());
        
        controller.insertarContacto();
        
        contactos = [select id, Nivel_de_Relaci_n__c, Otro_contacto_del_cliente__c, Tipo_de_Contacto__c, Reto__c from Retos_Contacto__c];
        
        system.assertEquals(1, contactos.size());
        
        controller.contactoIdABorrar = retoContacto1.id;
        
        controller.borrarContacto();
        
        contactos = [select id, Nivel_de_Relaci_n__c, Otro_contacto_del_cliente__c, Tipo_de_Contacto__c, Reto__c from Retos_Contacto__c];
        
        system.assertEquals(0, contactos.size());
        
        
    }
}