src/objects/Asociacion_de_producto_con_proyecto__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monto_Mensual__c</fullName>
        <label>Monto Mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monto_One__c</fullName>
        <label>Monto One</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Asociaciones de producto con proyecto</relationshipLabel>
        <relationshipName>Asociaciones_de_producto_con_proyecto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proyecto__c</fullName>
        <label>Proyecto</label>
        <referenceTo>Proyecto__c</referenceTo>
        <relationshipLabel>Asociaciones de producto con proyecto</relationshipLabel>
        <relationshipName>Asociaciones_de_producto_con_proyecto</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asociación de producto con proyecto</label>
    <nameField>
        <label>Nombre de Asociación de producto con proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asociaciones de producto con proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Proyecto__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ID_Delta__c</fullName>
        <label>ID Delta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Proyectos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Producto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Proyectos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Update_Project_batch__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monto_Mensual__c</fullName>
        <label>Monto Mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monto_uno__c</fullName>
        <label>Monto uno</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>idProyecto__c</fullName>
        <label>idProyecto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>idServicio__c</fullName>
        <label>idServicio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Update Project batch</label>
    <nameField>
        <label>Nombre de Update Project batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Update Projects batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateProy_preciosTest.cls
@isTest
public class UpdateProy_preciosTest {

    static testMethod void InsertoUnProyectoBatchYseActualizaLosPreciosDelProyecto() {
        Opportunity oportunidad = new Opportunity();
        oportunidad.name = 'nueva';
        oportunidad.CloseDate = Date.today();
        oportunidad.StageName = 'Contacto Inicial';
        insert oportunidad;
        
        Proyecto__c proyecto = new Proyecto__c();
        proyecto.ID_Delta__c = '123';
        proyecto.Oportunidad__c = oportunidad.id;
        insert proyecto;
        
        Product2 producto = new Product2();
        producto.externalId = '321';
        producto.name = 'nuevo';
        insert producto;
        
        Asociacion_de_producto_con_proyecto__c asociacion = new Asociacion_de_producto_con_proyecto__c();
        asociacion.proyecto__c = proyecto.id;
        asociacion.producto__c = producto.id;
        insert asociacion;
        
        Update_Project_batch__c batch = new Update_Project_batch__c();
        batch.idProyecto__c = '123';
        batch.cantidad__c = 1;
        batch.idServicio__c = '321';
        batch.Moneda__c = '$';
        batch.Monto_uno__c = 100;
        batch.Monto_Mensual__c = 50;
        insert batch;
        
        Asociacion_de_producto_con_proyecto__c unProyectoYaActualizado = [select id, cantidad__c, moneda__c, monto_one__c, monto_Mensual__c from Asociacion_de_producto_con_proyecto__c];
        
        system.assertEquals(1, unProyectoYaActualizado.cantidad__c);
        system.assertEquals('ARG', unProyectoYaActualizado.moneda__c);
        system.assertEquals(100, unProyectoYaActualizado.monto_one__c);
        system.assertEquals(50, unProyectoYaActualizado.monto_Mensual__c);
    }
    
    static testMethod void InsertoUnProyectoBatchYNoHayUnProyectoConEseId() {
        
        Update_Project_batch__c batch = new Update_Project_batch__c();
        batch.idProyecto__c = '123';
        batch.cantidad__c = 1;
        batch.Moneda__c = 'ARG';
        batch.Monto_uno__c = 100;
        batch.Monto_Mensual__c = 50;
        try{
            insert batch;
        }catch(Exception e){}
        
    }
}