src/objects/Business_Landscape__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Landscapes</relationshipLabel>
        <relationshipName>Business_Landscapes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Service__c</fullName>
        <label>Categoria de los servicios</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IoT</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
                <value>
                    <fullName>Comunicaciones unificadas y servicios de colaboración</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Otros servicios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Landscape</label>
    <nameField>
        <label>Nombre de Business Landscape</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Landscapes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Categoria_Servicio__c.object
<CustomObject>
    <label>Categoria de Servicio</label>
    <nameField>
        <label>Nombre de Categoria_Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categoria de Servicios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contenedor_de_hito2__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contenedor de hitos2</relationshipLabel>
        <relationshipName>Contenedor_de_hitos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contenedor de hito2</label>
    <nameField>
        <label>Nombre de Contenedor_de_hito2__c</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenedor de hitos2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Servicio__c.object
<CustomObject>
    <fields>
        <fullName>Categoria_Servicio__c</fullName>
        <label>Categoria de Servicio</label>
        <referenceTo>Categoria_Servicio__c</referenceTo>
        <relationshipLabel>Servicios</relationshipLabel>
        <relationshipName>Servicios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Servicio</label>
    <nameField>
        <label>Nombre de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountBusinessLandscapeTest.cls
@isTest
public class AccountBusinessLandscapeTest {

    static testMethod void test1(){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Contenedor_de_hito2__c contenedor2 = new Contenedor_de_hito2__c();
        contenedor2.name = 'Contenedor';
        contenedor2.Cuenta__c = cuenta.id;
        insert contenedor2;
        
        Categoria_Servicio__c categoria = new Categoria_Servicio__c();
        categoria.name = 'Categoria1';
		insert categoria;
        
        Servicio__c servicio = new Servicio__c();
        servicio.name = 'Servicio1';
        servicio.Categoria_Servicio__c = categoria.id;
		insert servicio;
        
        Business_Landscape__c business = new Business_Landscape__c();
        business.name = 'business';
        business.Account__c = cuenta.id;
        business.Category_Service__c = categoria.name;
        insert business;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        AccountBusinessLandscapeController controller = new AccountBusinessLandscapeController();
        
        controller.getItems();
        controller.getServicios();
        
        //controller.hitoAInsertar = hito;
        controller.contenedor = contenedor2;
        
        system.assertEquals(1, controller.categoriasDeServicios.size());
        system.assertEquals(1, controller.businessLandscapeList.size());
        
        controller.categoriaSeleccionada = categoria.name;
        controller.servicioSeleccionado = servicio.name;
        controller.add();
        
        system.assertEquals(2, controller.businessLandscapeList.size());
        
        controller.toDel = business.id;
        controller.del();
        
        controller.save();
        
        //List<Business_Landscape__c> prueba2 = new List<Business_Landscape__c>();
        //prueba2 = [select id from Business_Landscape__c];
        
        system.assertEquals(1, controller.businessLandscapeList.size());
    }
    
    
    static testMethod void test2(){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Contenedor_de_hito2__c contenedor2 = new Contenedor_de_hito2__c();
        contenedor2.name = 'Contenedor';
        contenedor2.Cuenta__c = cuenta.id;
        insert contenedor2;
        
        Categoria_Servicio__c categoria = new Categoria_Servicio__c();
        categoria.name = 'Categoria1';
		insert categoria;
        
        Servicio__c servicio = new Servicio__c();
        servicio.name = 'Servicio1';
        servicio.Categoria_Servicio__c = categoria.id;
		insert servicio;
        
        /*Business_Landscape__c business = new Business_Landscape__c();
        business.name = 'business';
        business.Account__c = cuenta.id;
        business.Category_Service__c = categoria.name;
        insert business;*/
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        AccountBusinessLandscapeController controller = new AccountBusinessLandscapeController();
        
        controller.siNoHayCreadoUnRegistroEnParqueDeServiciosGeneroUnoDeCadaUno();
        
        controller.contenedor = contenedor2;
        
        system.assertEquals(1, controller.categoriasDeServicios.size());
        
        List<Business_Landscape__c> prueba = new List<Business_Landscape__c>();
        prueba = [select id from Business_Landscape__c];
        
        system.assertEquals(20, prueba.size());
        
        controller.getExcelName();
        controller.ExportToExcel();
        
        
     }
    
}