src/objects/Contenedor_de_hito2__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contenedor de hitos2</relationshipLabel>
        <relationshipName>Contenedor_de_hitos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fecha_vencimiento_otros_servicios__c</fullName>
        <label>Fecha vencimiento otros servicios</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vencimiento_datos_fijos__c</fullName>
        <label>vencimiento datos fijos</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vencimiento_servicios_moviles__c</fullName>
        <label>vencimiento servicios moviles</label>
        <type>Date</type>
    </fields>
    <label>Contenedor de hito2</label>
    <nameField>
        <label>Nombre de Contenedor_de_hito2__c</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenedor de hitos2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contenedor_de_hito__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contenedor de hitos</relationshipLabel>
        <relationshipName>Contenedor_de_hitos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_vencimiento_otros_servicios__c</fullName>
        <label>Fecha vencimiento otros servicios</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vencimiento_datos_fijos__c</fullName>
        <label>vencimiento datos fijos</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vencimiento_servicios_moviles__c</fullName>
        <label>vencimiento servicios moviles</label>
        <type>Date</type>
    </fields>
    <label>Contenedor de hito</label>
    <nameField>
        <label>Nombre de Contenedor de hito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenedor de hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hito_Relevante_2__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vencimiento Contrato Activo con Nosotros</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato Activo con la Competencia</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP TI</fullName>
                </value>
                <value>
                    <fullName>Evento Para Nuestros Clientes</fullName>
                </value>
                <value>
                    <fullName>Evento Relevante de la Industria</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato del Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contenedor_de_hito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contenedor de hito2</label>
        <referenceTo>Contenedor_de_hito2__c</referenceTo>
        <relationshipLabel>Hitos Relevantes 2</relationshipLabel>
        <relationshipName>Hitos_Relevantes_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <label>Hito Relevante 2</label>
    <nameField>
        <label>Nombre de Hito Relevante 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos Relevantes 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hito_relevante__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vencimiento Contrato Activo con Nosotros</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato Activo con la Competencia</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP TI</fullName>
                </value>
                <value>
                    <fullName>Evento Para Nuestros Clientes</fullName>
                </value>
                <value>
                    <fullName>Evento Relevante de la Industria</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato del Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contenedor_de_hito__c</fullName>
        <label>Contenedor de hito</label>
        <referenceTo>Contenedor_de_hito__c</referenceTo>
        <relationshipLabel>Hitos relevantes</relationshipLabel>
        <relationshipName>Hitos_relevantes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <label>Hito relevante</label>
    <nameField>
        <label>Nombre de Hitos relevantes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos relevantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HitosRelevantesController.cls
public with sharing class HitosRelevantesController {
    
    public String idCuenta {get; set;}
    public Contenedor_de_hito2__c contenedor {get; set;}
    
    public String hitoABorrarId {get;set;}
    public Hito_Relevante_2__c hitoAInsertar {get; set;}
    
    public HitosRelevantesController(){
        
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
        
        
        hitoAInsertar = new Hito_Relevante_2__c();
        
        
        obtenerContenedores();  
        //insertarContenedor();
    }
    
    public void obtenerContenedores(){
        List<Contenedor_de_hito2__c> contenedores = new List<Contenedor_de_hito2__c>();
        
        contenedores = [select id, Fecha_vencimiento_otros_servicios__c, vencimiento_datos_fijos__c, vencimiento_servicios_moviles__c,
                        (select id, Categoria__c, Descripcion__c, Fecha__c from Hitos_Relevantes_2__r)
                        from Contenedor_de_hito2__c
                        where cuenta__c =: idCuenta
                        Limit 1];
        if(contenedores.size()>0){
            contenedor = contenedores[0];
        }
    }
    
    public void insertarContenedor(){
        if(contenedor == null){
            contenedor = new Contenedor_de_hito2__c();
            
            
            contenedor.Cuenta__c = idCuenta;
            
            
            
            insert contenedor;
            
            
        }
    }
    
    public void guardar(){
        
        update contenedor;
    }
    
    public PageReference BorrarHito(){
        
        Integer i = 0;
        
        for(Hito_Relevante_2__c hito : contenedor.Hitos_Relevantes_2__r){
            
            if(hito.id == hitoABorrarId){
                break;
            }
            else{
                i++;
            }   
        }
        
        
        if(contenedor.Hitos_Relevantes_2__r[i].id != null){
            
            List<task> aBorrar = new List <task>();
            if(Schema.sObjectType.task.isAccessible())
                aBorrar = [SELECT ID FROM task WHERE Hito_Relevante_2__c =: contenedor.Hitos_Relevantes_2__r[i].id];
            
            if(Task.sObjectType.getDescribe().isDeletable()){
                delete aBorrar;
            }
            
            if(Hito_relevante__c.sObjectType.getDescribe().isDeletable()){
                delete contenedor.Hitos_Relevantes_2__r[i];
            }
            
        }
        
        
        obtenerContenedores();
        return null;    	
        
    }
    
    public void insertHito(){
        
        insertarContenedor();
        
        
        hitoAInsertar.Contenedor_de_hito__c = contenedor.id;
        
        
        if(Hito_relevante__c.sObjectType.getDescribe().isCreateable()){ 
            
            insert hitoAInsertar;       
        }
        
        
        Task tareaDelHito = new Task();
        
        if(Schema.sObjectType.Task.fields.ActivityDate.isCreateable()){
            tareaDelHito.ActivityDate = hitoAInsertar.Fecha__c;
        }
        if(Schema.sObjectType.Task.fields.Subject.isCreateable()){
            tareaDelHito.Subject = hitoAInsertar.Categoria__c;
        }
        if(Schema.sObjectType.Task.fields.Description.isCreateable()){
            tareaDelHito.Description = hitoAInsertar.Descripcion__c;
        }
        if(Schema.sObjectType.Task.fields.WhatId.isCreateable()){
            tareaDelHito.WhatId = idCuenta;
        }
        
        tareaDelHito.Hito_Relevante_2__c = hitoAInsertar.id;

        
        if(Task.sObjectType.getDescribe().isCreateable()){ 
            
            insert tareaDelHito;      
        }
        
        
        
        hitoAInsertar = new Hito_Relevante_2__c();
        
        obtenerContenedores();
    }
    
}