src/objects/Contact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>Contacts_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Assessment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Influence__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Influenced__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influenced</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences</relationshipLabel>
        <relationshipName>Contact_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Influences__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influences</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences (Contact Influence)</relationshipLabel>
        <relationshipName>Contact_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Influence</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Influence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Influences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>competitorName__c</fullName>
        <label>Nombre de la Competencia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Billing_Start_Date__c</fullName>
        <label>Inicio Facturación</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Charges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ingreso recurrente mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Charges__c</fullName>
        <label>Ingreso por única vez</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/UtilTriggersTest.cls
@isTest
public class UtilTriggersTest {
	
    static testMethod void test (){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        Contract contrato = new Contract();
        contrato.competitorName__c = 'nombre';
        contrato.AccountId = cuenta.id;
        insert contrato;
        
        Contact contacto = new Contact();
        contacto.LastName = 'nombre';
        insert contacto;
        
        Contact_Influence__c influencia = new Contact_Influence__c();
        influencia.Contact_Influenced__c = contacto.id;
        influencia.Contact_Influences__c = contacto.id;
        insert influencia;
        
        Contact_Assessment__c ca = new Contact_Assessment__c();
        ca.Contact__c = contacto.id;
        insert ca;
        
        Opportunity oportunidad = new Opportunity();
        oportunidad.Estimated_Billing_Start_Date__c = Date.today();
        oportunidad.Monthly_Charges__c = 222;
        oportunidad.Unique_Charges__c = 800;
        oportunidad.Name = 'dasdas';
        oportunidad.StageName = 'Qualification';
        oportunidad.CloseDate = Date.today();
        insert oportunidad;
        
        Event evento = new Event();
        evento.Description = 'dkahsdkjashdjksadhjsa';
        evento.DurationInMinutes = 12;
        evento.ActivityDateTime = Date.today();
		insert evento;
        
        Task tarea = new Task();
        tarea.Description = 'dhaksjdhajs';
        insert tarea;
            
        List<Contract> contractList = new List<Contract>();
        contractList.add(contrato);
        UtilTriggers.ContractTrigger(contractList);
        
        List<Contact> contactList = new List<Contact>();
        contactList.add(contacto);
        UtilTriggers.deleteContactInfluences(contactList);
        
        List<Opportunity> oportunityList = new List<Opportunity>();
        oportunityList.add(oportunidad);
        
        UtilTriggers.opportunitySetCurrentYearCharges(oportunityList);
        
        List<Event> lista = new List<Event>();
        lista.add(evento);
        
        UtilTriggers.rellenaDescripcionEvent(lista);
        
        List<Task> lista2 = new List<Task>();
        lista2.add(tarea);
        
        UtilTriggers.rellenaDescripcionTask(lista2);
        
        List<Account> listaCuentas = new List<Account>();
        listaCuentas.add(cuenta);
        
        Map<Id,Account> mapa = new map<Id, Account>();
        
        UtilTriggers.setStrategicContextLastUpdate(listaCuentas, mapa, true);
        
        List<Opportunity> oportunidades = [select id from opportunity];
        
        system.assertEquals(1, oportunidades.size());
    }
}