src/objects/Contact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Attitudes__c</fullName>
        <label>Attitudes</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Burning Platform</fullName>
                </value>
                <value>
                    <fullName>Statu Quo</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Authority__c</fullName>
        <label>Authority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Cycle__c</fullName>
        <label>Buying Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awareness of Needs</fullName>
                </value>
                <value>
                    <fullName>Assessments of Alternatives</fullName>
                </value>
                <value>
                    <fullName>Alleviation of Risks</fullName>
                </value>
                <value>
                    <fullName>Achievements of Results</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competing_Company_Relationship__c</fullName>
        <label>Competing Company Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Positive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Focus__c</fullName>
        <label>Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Generation__c</fullName>
        <label>Generation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Influence__c</fullName>
        <label>Influence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Our_Relationship__c</fullName>
        <label>Our Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Assessment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Buying_Cycle__c</fullName>
        <label>Buying Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awareness of Needs</fullName>
                </value>
                <value>
                    <fullName>Assessments of Alternatives</fullName>
                </value>
                <value>
                    <fullName>Alleviation of Risks</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
                <value>
                    <fullName>Achievements of Results</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/test_OpportunityEvaluations.cls
@isTest
private class test_OpportunityEvaluations {
	    
    static testMethod void myUnitTest() {
    	
    	Account acctParent=new Account();
        acctParent.Name='test';
        acctParent.industry = 'Banking';
        
        insert acctParent;
    	
    	Account acct=new Account();
        acct.Name='test';
        acct.industry = 'Banking';
        acct.ParentId = acctParent.id;
        
        insert acct;
        
        Contact contact = new Contact();
        contact.LastName = 'test';
        contact.AccountId = acct.id;
        insert contact;
        
        Contact contact2 = new Contact();
        contact2.LastName = 'test';
        contact2.AccountId = acctParent.id;
        insert contact2;
        
        System.currentPagereference().getParameters().put('id',acct.id);
        OpportunityEvaluations p = new OpportunityEvaluations();
        
        system.assertEquals(1, p.getNotEvaluated().size());
        system.assertEquals(1, p.contatsFromParents.size());
        
        p.contactIdToEvaluate = contact.id;
        p.popContactEvaluation();
        
        p.newEval.Focus__c = 'End User';
        p.newEval.Attitudes__c = 'Negative';
        p.newEval.Authority__c = 'Positive';
        p.newEval.Influence__c = 'Negative';
        p.newEval.Our_Relationship__c = 'Positive';
        p.newEval.Competing_Company_Relationship__c = 'Positive';
        p.newEval.Generation__c = 'X';
        p.newEval.Buying_Cycle__c = 'Assessments of Alternatives';
        
        p.InsertEvaluation();
        system.assertEquals(0, p.getNotEvaluated().size());
        system.assertEquals(1, p.evaluated.size());
        
        List<Contact_Assessment__c> contactAssesmentList = [select id from Contact_Assessment__c];
        system.assertEquals(1, contactAssesmentList.size());
        
        p.contactIdToEvaluate = contact2.id;
        p.popContactEvaluation();
        
        p.newEval.Focus__c = 'End User';
        p.newEval.Attitudes__c = 'Negative';
        p.newEval.Authority__c = 'Positive';
        p.newEval.Influence__c = 'Negative';
        p.newEval.Our_Relationship__c = 'Positive';
        p.newEval.Competing_Company_Relationship__c = 'Positive';
        p.newEval.Generation__c = 'X';
        p.newEval.Buying_Cycle__c = 'Assessments of Alternatives';
        
        p.InsertEvaluation();
        system.assertEquals(0, p.contatsFromParents.size());
        system.assertEquals(2, p.evaluated.size());
        
        List<Contact_Assessment__c> contactAssesmentList1 = [select id from Contact_Assessment__c];
        system.assertEquals(2, contactAssesmentList1.size());
        
        p.evaluated.get(0).Influence__c = 'Positive';
        p.SaveChanges();
        
        List<Contact_Assessment__c> contactAssesmentList2 = [select id,Influence__c from Contact_Assessment__c where id = :p.evaluated.get(0).id];
        system.assertEquals('Positive', contactAssesmentList2.get(0).Influence__c);
        
        p.delid = contactAssesmentList2.get(0).id;
        p.DeleteEvaluation();
        
		system.assertEquals(1, p.evaluated.size());
		                
        List<Contact_Assessment__c> contactAssesmentList3 = [select id from Contact_Assessment__c];
        system.assertEquals(1, contactAssesmentList3.size());
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Open';
        opp.CloseDate = System.Today();
        opp.accountId = acct.id;
        insert opp;
        
        System.currentPagereference().getParameters().put('id',opp.id);
        OpportunityEvaluations p1 = new OpportunityEvaluations();
        
        p1.copyRDM();
        
        OpportunityEvaluations p2 = new OpportunityEvaluations();
        system.assertEquals(1, p2.evaluated.size());
        
        p2.getFooterStyle();
        
        p2.evaluated.get(0).Focus__c = null;
        p2.evaluated.get(0).Attitudes__c = null;
        p2.evaluated.get(0).Authority__c = null;
        p2.evaluated.get(0).Influence__c = null;
        p2.evaluated.get(0).Our_Relationship__c = null;
        p2.evaluated.get(0).Competing_Company_Relationship__c = null;
        p2.evaluated.get(0).Generation__c = null;
        p2.evaluated.get(0).Buying_Cycle__c = null;
        
        p2.SaveChanges();
        
        
    }
}