src/objects/CotizacionDollarBudget__c.object
<CustomObject>
    <fields>
        <fullName>Cotizacion__c</fullName>
        <label>Cotizacion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Cotizacion Dollar Budget</label>
    <nameField>
        <label>Nombre de CotizacionDollarBudget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotizaciones Dollar Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dolar_Buget__c</fullName>
        <label>Dolar Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/DollarBudgetUpdateBatch.cls
global class DollarBudgetUpdateBatch implements Database.Batchable<sObject>{
   
    global final String Query;
	global final CotizacionDollarBudget__c DollarBudget;
    
    global DollarBudgetUpdateBatch(String q, CotizacionDollarBudget__c db){
        Query=q;
        DollarBudget=db;
    }

    
    global Database.QueryLocator start(Database.BatchableContext bc) {
         return Database.getQueryLocator(Query);
    }

    
    global void execute(Database.BatchableContext BC, list<Opportunity> oportunidades){
        for(Opportunity op : oportunidades){
            op.Dolar_Buget__c = DollarBudget.Cotizacion__c;
        }
        update oportunidades;
    }

    global void finish(Database.BatchableContext BC){
        
    }

    
}