src/objects/CotizacionDollarBudget__c.object
<CustomObject>
    <fields>
        <fullName>Cotizacion__c</fullName>
        <label>Cotizacion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Cotizacion Dollar Budget</label>
    <nameField>
        <label>Nombre de CotizacionDollarBudget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotizaciones Dollar Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dolar_Buget__c</fullName>
        <label>Dolar Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/OpportunityTriggerTest.cls
@isTest
public class OpportunityTriggerTest {
    
    static testMethod void seGeneraUnaOportunidadYSeLeCargaLaUltimaCotizacion() {
        
        CotizacionDollarBudget__c unaCotizacion = new CotizacionDollarBudget__c();
        unaCotizacion.Cotizacion__c = 12;
        insert unaCotizacion;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'oportunidad'; 
        opp.StageName = 'etapa'; 
        opp.CloseDate = Date.today();
        insert opp;
        
        Opp = [select id, Dolar_Buget__c from opportunity];
        
        system.assertEquals(12, opp.Dolar_Buget__c);

    }
}