src/objects/customReport__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SCP Custom Report</relationshipLabel>
        <relationshipName>SCP_Custom_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Custom Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Custom Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Custom Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AccountCustomReport.cls
@isTest
private class Test_AccountCustomReport {

    static testMethod void myUnitTest() {
        Account myAccount=new Account(Name = 'Test');
        insert myAccount;
        
        PageReference pageRef = Page.AccountCustomReport;
        Test.setCurrentPage(pageRef);       
        System.currentPagereference().getParameters().put('id',myAccount.id);
        
        AccountCustomReportController acr = new AccountCustomReportController();
        acr.save();
        
        List<CustomReport__c> customReports = [select id from CustomReport__c where account__c = :myAccount.id];
        system.assertEquals(1, customReports.size());
        system.assertEquals(customReports.get(0).id, acr.customReport.id);
        
        AccountCustomReportController acr2 = new AccountCustomReportController();
        acr2.ExportToWord();
        acr2.getWordName();
        
                
    }
}