src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Industria y Comercio</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Administración pública</fullName>
                </value>
                <value>
                    <fullName>Salud, Educación y Seguridad</fullName>
                </value>
                <value>
                    <fullName>Servicios y Tecnología</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Trend</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IndsutryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_adminIndustryTrends.cls
@isTest
private class test_adminIndustryTrends {

    static testMethod void myUnitTest() {
		
		Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionRegional.id);
        insert regionLocal;
        
        adminIndustryTrends p = new adminIndustryTrends();
        
        p.getRegions();
        p.getSectors();
        p.getIndustries();
        
        p.regionId = regionGlobal.id;
        p.sector = 'Private';
        p.industry = 'Industry';
        
        p.doUpdate();
        
        p.tempAccount.Micro_Industry__c = 'Micro Industry';
        
        p.doUpdate();        
        system.assertEquals(0, p.getTrends().size());
        List<Industry_Trend__c> trendsList = [select id from Industry_Trend__c];
        system.assertEquals(0, trendsList.size());
        
        p.newTrend.Title__c = 'Title';
        p.newTrend.Trend__C = 'Trend__c';
        p.InsertNewTrend();
        
        system.assertEquals(1, p.getTrends().size());
        List<Industry_Trend__c> trendsList2 = [select id,Industry__c,Sub_Sector__c from Industry_Trend__c];

        
        p.getTrends().get(0).Trend__c = 'Updated';
        p.save();
        
        List<Industry_Trend__c> trendsList3 = [select id,Trend__c from Industry_Trend__c];
        system.assertEquals('Updated', trendsList3.get(0).Trend__c);
         
		p.IdtoDel = p.getTrends().get(0).id;        
        p.getHashIndustry();
        p.del();
        
        List<Industry_Trend__c> trendsList4 = [select id from Industry_Trend__c];
    }
}