src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_FCV_Calculated__c</fullName>
        <description>Field to calculate the sum of Estimated in Suboportunities</description>
        <inlineHelpText>Adding up the estimated FCV of the sub opportunities win or in progress (not loss or cancelled)
Is the FCV considered for commercial dashboard and reporting
Posible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <description>Estimated by the account manager in early stages of the opportunity (m€)</description>
        <inlineHelpText>The account manager indicates an estimation of the total value of the project.
Posible Values: Free field in €
Filled in by: The account manager.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Year_End_Revenue__c</fullName>
        <label>Ingresos Totales año fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Contract_Value__c</fullName>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Charges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ingreso recurrente mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Forecasted_FCV__c</fullName>
        <description>Field in the header of a opportunity. It is based in 2 fields calculated via trigger and sums in the subopportunities</description>
        <formula>Estimated_FCV_Calculated__c * Calculated_Win_Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>= Calculated FCV * calculated win probability
Possible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Charges__c</fullName>
        <label>Ingreso por única vez</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unsold_Pipeline__c</fullName>
        <formula>Valor_Total_del_Contrato_calculado__c*Probability</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valor total del Contrato (FCV) (pond.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_Total_del_Contrato_calculado__c</fullName>
        <formula>Monthly_Charges__c * contract_duration_months__c + Unique_Charges__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valor total del Contrato (FCV)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weighted_Estimated_Year_End_Revenue__c</fullName>
        <formula>Estimated_Year_End_Revenue__c * Probability</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ingresos Totales año fiscal (pond.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>contract_duration_months__c</fullName>
        <label>Duración del contrato (meses)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/test_owrap.cls
@isTest
private class test_owrap {

    static testMethod void myUnitTest() {
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.industry = 'Banking';        
        insert cuenta;
        
        Opportunity opp = new Opportunity(Name='test opportunity');
        opp.StageName = 'Open';
        opp.CloseDate = System.Today();
        opp.accountId = cuenta.Id;
        
        Owrap o = new Owrap(opp);       
        system.assertEquals(0,o.opp2.Amount);

        system.assertEquals(null,o.getFull_Contract_Value()); 
        system.assertEquals(null,o.getUnique_Charges());
        system.assertEquals(null,o.getMonthly_Charges());
        system.assertEquals(null,o.getEstimated_Year_End_Revenue());
        system.assertEquals(null,o.getUnsold_Pipeline());
        system.assertEquals(null,o.getWeighted_Estimated_Year_End_Revenue());
        system.assertEquals(null,o.getEstimated_FCV());
        system.assertEquals(null,o.getEstimated_FCV_Calculated());
        system.assertEquals(null,o.getTotal_Forecasted_FCV());
        


        opp.Estimated_Year_End_Revenue__c = 10;
        opp.Full_Contract_Value__c = 10;
        opp.Unique_Charges__c = 10;
        opp.Monthly_Charges__c = 10;
        opp.Estimated_FCV__c = 10;
        opp.Estimated_FCV_Calculated__c = 10;
        opp.Contract_duration_months__c = 1;

        String userCurrency;       
        if(Util.checkMultiCurrencyEnabled()){
            userCurrency = UserInfo.getDefaultCurrency();
            opp.put('CurrencyIsoCode',userCurrency);
        } else {
            userCurrency = '$';
        }
        
        opp.Probability = 10;
        insert opp;    

        Opportunity oppResult = [select id, Total_Forecasted_FCV__c, Weighted_Estimated_Year_End_Revenue__c, Probability, Valor_Total_del_Contrato_calculado__c, Unsold_Pipeline__c, Estimated_Year_End_Revenue__c, Full_Contract_Value__c, Unique_Charges__c, Monthly_Charges__c, Estimated_FCV__c, Estimated_FCV_Calculated__c, Contract_duration_months__c from Opportunity where id = :opp.id];
        Decimal valor_Total_del_Contrato_calculado = opp.Monthly_Charges__c * opp.Contract_duration_months__c + opp.Unique_Charges__c;
        system.assertEquals(valor_Total_del_Contrato_calculado, oppResult.Valor_Total_del_Contrato_calculado__c);
        system.assertEquals(valor_Total_del_Contrato_calculado * opp.Probability / 100,oppResult.Unsold_Pipeline__c);

        Owrap o2 = new Owrap(oppResult);        

        system.assertEquals(userCurrency + '10',o2.getFull_Contract_Value()); 
        system.assertEquals(userCurrency + '10',o2.getUnique_Charges());
        system.assertEquals(userCurrency + '10',o2.getMonthly_Charges());
        system.assertEquals(userCurrency + '10',o2.getEstimated_Year_End_Revenue());
        system.assertEquals(userCurrency + '2',o2.getUnsold_Pipeline());
        system.assertEquals(userCurrency + '1',o2.getWeighted_Estimated_Year_End_Revenue());
        system.assertEquals(userCurrency + '10',o2.getEstimated_FCV());
        system.assertEquals(userCurrency + '10',o2.getEstimated_FCV_Calculated());
        o2.getTotal_Forecasted_FCV();
        
    }
}