src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_FCV_Calculated__c</fullName>
        <description>Field to calculate the sum of Estimated in Suboportunities</description>
        <inlineHelpText>Adding up the estimated FCV of the sub opportunities win or in progress (not loss or cancelled)
Is the FCV considered for commercial dashboard and reporting
Posible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <description>Estimated by the account manager in early stages of the opportunity (m€)</description>
        <inlineHelpText>The account manager indicates an estimation of the total value of the project.
Posible Values: Free field in €
Filled in by: The account manager.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Year_End_Revenue__c</fullName>
        <label>Ingresos Totales año fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Contract_Value__c</fullName>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Charges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ingreso recurrente mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Forecasted_FCV__c</fullName>
        <description>Field in the header of a opportunity. It is based in 2 fields calculated via trigger and sums in the subopportunities</description>
        <formula>Estimated_FCV_Calculated__c * Calculated_Win_Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>= Calculated FCV * calculated win probability
Possible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>SCP Dep</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Charges__c</fullName>
        <label>Ingreso por única vez</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unsold_Pipeline__c</fullName>
        <formula>Valor_Total_del_Contrato_calculado__c*Probability</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valor total del Contrato (FCV) (pond.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weighted_Estimated_Year_End_Revenue__c</fullName>
        <formula>Estimated_Year_End_Revenue__c * Probability</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ingresos Totales año fiscal (pond.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/owrap.cls
public with sharing class owrap{
    
        public Opportunity opp {get;set;}
        public Opportunity opp2 {get;set;}
        private static Map<String,Decimal> map_currency {get;set;}
        
        public owrap(Opportunity opp){
 
            initCurrency();        
            this.opp = opp;
            this.opp2 = new Opportunity();
            if(opp.Estimated_Year_End_Revenue__c == null || opp.Probability == null){
                opp2.Amount = 0;
            }else{
                opp2.Amount = opp.Estimated_Year_End_Revenue__c * opp.Probability / 100;
            }
        
        }
        
        private String getUserCurrency() {
            if (Util.checkMultiCurrencyEnabled()) {
                return UserInfo.getDefaultCurrency();
            } else {
                return '$';
            }
        }
        
        public String getFull_Contract_Value() { 
          if (opp.Full_Contract_Value__c != null) {    
              Decimal result;
              if (Util.checkMultiCurrencyEnabled()) {
                  result = opp.Full_Contract_Value__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());                             
              } else {
                  result = opp.Full_Contract_Value__c;
                  return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));              
              }              
              return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));  
            } else {
              return null;
            }
        }
        
        public String getUnique_Charges() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Unique_Charges__c+'').replace('.',','));
            if (opp.Unique_Charges__c != null){
               Decimal result;
               
               if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Unique_Charges__c/map_currency.get((String) opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());                   
               }else{
                    result = opp.Unique_Charges__c;   
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
               }
               return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
               return null;
            }   
        }
        
        public String getMonthly_Charges(){            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Monthly_Charges__c+'').replace('.',','));
            if (opp.Monthly_Charges__c != null){
                Decimal result;
                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Monthly_Charges__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Monthly_Charges__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;
            }
        }
        
        public String getEstimated_Year_End_Revenue() {  
            if (opp.Estimated_Year_End_Revenue__c != null){
                Decimal result;
                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Estimated_Year_End_Revenue__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Estimated_Year_End_Revenue__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;
            }            
        }
        public String getUnsold_Pipeline() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Unsold_Pipeline__c+'').replace('.',','));

            if (opp.Unsold_Pipeline__c != null){
                Decimal result;
            
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Unsold_Pipeline__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Unsold_Pipeline__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;
            }
        }
        
        public String getWeighted_Estimated_Year_End_Revenue() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Weighted_Estimated_Year_End_Revenue__c+'').replace('.',','));
            if (opp.Weighted_Estimated_Year_End_Revenue__c != null){
                Decimal result;
                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Weighted_Estimated_Year_End_Revenue__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Weighted_Estimated_Year_End_Revenue__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;    
            }
        }       
                
        public String getEstimated_FCV() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Weighted_Estimated_Year_End_Revenue__c+'').replace('.',','));
            if (opp.Estimated_FCV__c != null){
                Decimal result;                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Estimated_FCV__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Estimated_FCV__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;    
            }
        }
        
        public String getEstimated_FCV_Calculated() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Weighted_Estimated_Year_End_Revenue__c+'').replace('.',','));
            if (opp.Estimated_FCV_Calculated__c != null){
                Decimal result;                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Estimated_FCV_Calculated__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Estimated_FCV_Calculated__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;    
            }
        }        
        
        public String getTotal_Forecasted_FCV() {            
//            return UserInfo.getDefaultCurrency() + ' ' + Util.transforma_miles((opp.Weighted_Estimated_Year_End_Revenue__c+'').replace('.',','));
            if (opp.Total_Forecasted_FCV__c != null){
                Decimal result;                
                if (Util.checkMultiCurrencyEnabled()) {
                    result = opp.Total_Forecasted_FCV__c/map_currency.get((String)opp.get('CurrencyIsoCode'))*map_currency.get(getUserCurrency());
                }else{
                    result = opp.Total_Forecasted_FCV__c;
                    return getUserCurrency() + Util.transforma_miles((result+'').replace('.',','));
                }
                
                return getUserCurrency() + ' ' + Util.transforma_miles((result+'').replace('.',','));
            }else{
                return null;    
            }
        }
        
        private static void initCurrency() {                        
            if (map_currency == null) { 
                /*
                List<CurrencyType> ratios=[select IsoCode, ConversionRate from CurrencyType];
                map_currency=new Map<String,Decimal>();
                for(CurrencyType ct:ratios) {
                    map_currency.put(ct.IsoCode,ct.ConversionRate);
                }
                */
                map_currency = Util.getCurrencyMap();
                system.debug('>>>>> map_currency == null -> map_currency: ' + map_currency);
            } else {
                system.debug('>>>>> map_currency != null -> map_currency: ' + map_currency);            
            }          
        }
    }