src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Casos de exito en la cuenta</fullName>
                </value>
                <value>
                    <fullName>Diferenciadores competitivos en la cuenta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_AdminProvenValueController.cls
@isTest
private class Test_AdminProvenValueController {

    static testMethod void myUnitTest() {
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionRegional = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionRegional;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionRegional.id);
        insert regionLocal;
        
        AdminProvenValueController p = new AdminProvenValueController();
        
        p.getRegions();
        p.getIndustries();
        p.getMicro_Industries();
        p.getProvenValueTypes();
        
        p.regionId = regionGlobal.id;
        p.industry = 'Industry';
        p.micro_industry = 'Micro_industry';
        
        p.doUpdate();
        
        p.tempAccount.Industry = 'Industry';
        p.tempAccount.Micro_Industry__c = 'Micro Industry';
        
        p.doUpdate();        
        system.assertEquals(0, p.provenValueList.size());
        List<PastProvenValueNew__c> provenList = [select id from PastProvenValueNew__c];
        system.assertEquals(0, provenList.size());
        
        p.newPruvenValue.Unique_Value__c = 'value';
        p.newPruvenValue.Type__c = 'type';
        p.InsertNew();
        
        system.assertEquals(1, p.provenValueList.size());
        List<PastProvenValueNew__c> provenValueList2 = [select id,Industry__c,Micro_Industry__c from PastProvenValueNew__c];
        system.assertEquals('Micro Industry', provenValueList2.get(0).Micro_Industry__c);     
        system.assertEquals('Industry', provenValueList2.get(0).Industry__c);
        
        p.provenValueList.get(0).Unique_Value__c = 'Updated';
        p.save();
        
        List<PastProvenValueNew__c> provenValueList3 = [select id,Unique_Value__c from PastProvenValueNew__c];
        system.assertEquals('Updated', provenValueList3.get(0).Unique_Value__c);
        
		p.IdtoDelete = p.provenValueList.get(0).id;        
        p.del();
        
        List<PastProvenValueNew__c> provenValueList4 = [select id from PastProvenValueNew__c];
        system.assertEquals(0, provenValueList4.size());
 		       
    }

}