src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Update_Service_batch__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>categoria__c</fullName>
        <label>categoria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>idDelta__c</fullName>
        <label>idDelta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Update Service batch</label>
    <nameField>
        <label>Nombre de Update Service batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Update Service batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateServiceTest.cls
@isTest
public class UpdateServiceTest {

    static testMethod void InsertoUnServicioBatchYSeCreaUnProducto(){
        
        PriceBook2 pb = New PriceBook2(Id = test.getStandardPricebookId(), isActive = true);
        update pb;
        
        Update_Service_batch__c batch = new Update_Service_batch__c(); 
        batch.Name__c = 'Nombre';
        batch.categoria__c = 'Digital';
        batch.idDelta__c = 123;
        
        insert batch;
        
        Product2 producto = [select id, name, family, ExternalId from product2];
        
        system.assertEquals('Nombre', producto.name);
        system.assertEquals('Digital', producto.family);
        system.assertEquals('123', producto.ExternalId);
    }
    
    static testMethod void InsertoUnServicioBatchYaExistenteYNoSeDuplica(){
        
        PriceBook2 pb = New PriceBook2(Id = test.getStandardPricebookId(), isActive = true);
        update pb;
        
        Update_Service_batch__c batch = new Update_Service_batch__c();
        batch.Name__c = 'Nombre';
        batch.categoria__c = 'Digital';
        batch.idDelta__c = 123;
        
        insert batch;
        
        Product2 producto = [select id, name, family, ExternalId from product2];
        
        system.assertEquals('Nombre', producto.name);
        system.assertEquals('Digital', producto.family);
        system.assertEquals('123', producto.ExternalId);
        
        Update_Service_batch__c batch2 = new Update_Service_batch__c();
        batch2.Name__c = 'Nombre';
        batch2.categoria__c = 'Digital';
        batch2.idDelta__c = 123;
        
        insert batch2;
        
        List<Product2> productos = [select id, name, family, ExternalId from product2];
        
        system.assertEquals(1, productos.size());
    }
        
}