src/objects/Proyecto__c.object
<CustomObject>
    <fields>
        <fullName>Estado__c</fullName>
        <label>Estado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Delta__c</fullName>
        <label>ID Delta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Proyectos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Update_Project_Estado_batch__c.object
<CustomObject>
    <fields>
        <fullName>estado__c</fullName>
        <label>estado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>idProyecto__c</fullName>
        <label>idProyecto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Update Project Estado batch</label>
    <nameField>
        <label>Nombre de Update Project Estado batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Update Project Estado batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Update_Project_EstadoTest.cls
@isTest
public class Update_Project_EstadoTest {

    static testMethod void InsertoUnProyectoBatchYseActualizaElEstadoDelProyecto() {
        
        Opportunity oportunidad = new Opportunity();
        oportunidad.name = 'nueva';
        oportunidad.CloseDate = Date.today();
        oportunidad.StageName = 'Contacto Inicial';
        insert oportunidad;
        
        Proyecto__c proyecto = new Proyecto__c();
        proyecto.ID_Delta__c = '123';
        proyecto.Oportunidad__c = oportunidad.id;
        insert proyecto;
        
		Update_Project_Estado_batch__c batch = new Update_Project_Estado_batch__c();
		batch.idProyecto__c = '123';
        batch.estado__c = 'un estado';
        
        insert batch;
        
        Proyecto__c unProyectoYaActualizado = [select id, estado__c from Proyecto__c];
        
        system.assertEquals('un estado', unProyectoYaActualizado.estado__c);
        
    }
    
    static testMethod void InsertoUnProyectoBatchYNoHayUnProyectoConEseId() {
        
        Update_Project_Estado_batch__c batch = new Update_Project_Estado_batch__c();
        batch.idProyecto__c = '123';
        batch.estado__c = 'un estado';
        
        try{
            insert batch;
        }catch(Exception e){}
        
    }
}