src/objects/Value_Chain__c.object
<CustomObject>
    <fields>
        <fullName>Function__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCP Value Chain Function</label>
        <referenceTo>VCFunction__c</referenceTo>
        <relationshipName>SCP_Value_Chain</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Value Chain</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Value Chain</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Value Chain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VCFunction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SCP_Value_Chain_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Value Chain Function</label>
    <nameField>
        <label>Nombre de SCP Function</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Value Chain Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accountValueChainTableTest.cls
@isTest
public class accountValueChainTableTest {

    static testMethod void test(){
        
        Account cuenta = new Account();
        cuenta.name = 'CuentaPrueba';
        insert cuenta;
        
        VCFunction__c funcion = new VCFunction__c();
        funcion.name = 'nombre';
        funcion.Account__c = cuenta.id;
        insert funcion;
        
        Value_Chain__c value = new Value_Chain__c();
        //value.Name = 'nombrevalue';
        value.Function__c = funcion.id;
        insert value;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(cuenta);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(cuenta.id));
        accountValueChainTableController controller = new accountValueChainTableController();
        
        controller.getFunctionList();
        controller.newFunction();
        controller.saveChanges();
        
        controller.functionId = funcion.id;
        controller.deleteFunction();
        
        controller.vcId = value.id;
        controller.deleteVC();
     
        system.assertEquals(0, controller.functionSortList.size());
    }
    
}